/** Spanish for the Exchange tracker and the map. */
export const BOARD_ES = {
  "Exchange": "Intercambio",
  "Map": "Mapa",
  "Table": "Mesa",
  "Named opponent": "Oponente con nombre",
  "Acted": "Ha actuado",
  "Waiting": "Esperando",
  "Remove": "Quitar",
  "Up now": "Le toca",
  "Add someone...": "Añadir a alguien...",
  "or a name": "o un nombre",
  "No fight running.": "No hay pelea en curso.",
  "Next Exchange": "Siguiente Intercambio",
  "End fight": "Terminar la pelea",
  "Start fight": "Empezar la pelea",
  "Fill from the table": "Rellenar con la mesa",
  "An Exchange is every character acting in fictional order, then one action from each Threat and one from each named opponent.": "Un Intercambio es cada personaje actuando en orden ficticio, y después una acción de cada Amenaza y una de cada oponente con nombre.",
  "Nobody in the order yet.": "Todavía no hay nadie en el orden.",
  "The fight is over.": "La pelea ha terminado.",
  "No map": "Sin mapa",
  "Upload an image...": "Subir una imagen...",
  "Grid": "Cuadrícula",
  "Snap": "Ajustar",
  "Square": "Casilla",
  "Token": "Ficha",
  "Show": "Mostrar",
  "Hide": "Ocultar",
  "Pick a map to show the table.": "Elige un mapa para mostrarlo a la mesa.",
  "The GM has not shown a map.": "El DJ no ha mostrado ningún mapa.",
  "Loading the map...": "Cargando el mapa...",
  "No picture": "Sin imagen",
  "Add a token": "Añadir una ficha",
  "Who": "Quién",
  "Someone else": "Otra persona",
  "Picture": "Imagen",
  "Colour": "Color",
  "Size": "Tamaño",
  "Hidden from the players": "Oculta para los jugadores",
  "That image could not be read.": "No se pudo leer esa imagen.",
  "Drag on the map to measure in squares": "Arrastra sobre el mapa para medir en casillas",
  "Measure": "Medir",
  "Fog of war": "Niebla de guerra",
  "Reveal": "Revelar",
  "Cover up": "Ocultar zona",
  "Reveal all": "Revelar todo",
  "Cover all": "Ocultar todo",
  "Reveal the squares around the selected token": "Revela las casillas alrededor de la ficha seleccionada",
  "Around token": "Alrededor de la ficha",
  "Squares": "Casillas",
  "square": "casilla",
  "squares": "casillas",
  "Sound on": "Sonido activado",
  "Sound off": "Sonido apagado",
  "Turn timer": "Temporizador de turno",
  "Time per turn": "Tiempo por turno",
  "No timer": "Sin temporizador",
  "Pause": "Pausa",
  "Start": "Iniciar",
  "Reset": "Reiniciar",
  "Auto": "Auto",
  "Red": "Rojo", "Orange": "Naranja", "Gold": "Dorado", "Green": "Verde", "Teal": "Turquesa", "Blue": "Azul", "Purple": "Morado", "White": "Blanco"
};
