/** Spanish for the Exchange tracker and the map. */
export const BOARD_ES = {
  "Exchange": "Intercambio",
  "Map": "Mapa",
  "Table": "Mesa",
  "Named opponent": "Oponente con nombre",
  "Acted": "Ha actuado",
  "Waiting": "Esperando",
  "Remove": "Quitar",
  "Up now": "Le toca",
  "Add someone...": "Añadir a alguien...",
  "or a name": "o un nombre",
  "No fight running.": "No hay pelea en curso.",
  "Next Exchange": "Siguiente Intercambio",
  "End fight": "Terminar la pelea",
  "Start fight": "Empezar la pelea",
  "Fill from the table": "Rellenar con la mesa",
  "An Exchange is every character acting in fictional order, then one action from each Threat and one from each named opponent.": "Un Intercambio es cada personaje actuando en orden ficticio, y después una acción de cada Amenaza y una de cada oponente con nombre.",
  "Nobody in the order yet.": "Todavía no hay nadie en el orden.",
  "The fight is over.": "La pelea ha terminado.",
  "No map": "Sin mapa",
  "Upload an image...": "Subir una imagen...",
  "Grid": "Cuadrícula",
  "Snap": "Ajustar",
  "Square": "Casilla",
  "Token": "Ficha",
  "Show": "Mostrar",
  "Hide": "Ocultar",
  "Pick a map to show the table.": "Elige un mapa para mostrarlo a la mesa.",
  "The GM has not shown a map.": "El DJ no ha mostrado ningún mapa.",
  "Loading the map...": "Cargando el mapa...",
  "No picture": "Sin imagen",
  "Add a token": "Añadir una ficha",
  "Who": "Quién",
  "Someone else": "Otra persona",
  "Picture": "Imagen",
  "Colour": "Color",
  "Size": "Tamaño",
  "Hidden from the players": "Oculta para los jugadores",
  "That image could not be read.": "No se pudo leer esa imagen.",
  "Drag on the map to measure in squares": "Arrastra sobre el mapa para medir en casillas",
  "Measure": "Medir",
  "Fog of war": "Niebla de guerra",
  "Reveal": "Revelar",
  "Cover up": "Ocultar zona",
  "Reveal all": "Revelar todo",
  "Cover all": "Ocultar todo",
  "Reveal the squares around the selected token": "Revela las casillas alrededor de la ficha seleccionada",
  "Around token": "Alrededor de la ficha",
  "Squares": "Casillas",
  "square": "casilla",
  "squares": "casillas",
  "Sound on": "Sonido activado",
  "Sound off": "Sonido apagado",
  "Turn timer": "Temporizador de turno",
  "Time per turn": "Tiempo por turno",
  "No timer": "Sin temporizador",
  "Pause": "Pausa",
  "Start": "Iniciar",
  "Reset": "Reiniciar",
  "Auto": "Auto",
  "Spend one": "Gastar una",
  "Add one": "Añadir una",
  "Condition": "Condición",
  "{name} is burning and takes Hurt.": "{name} arde y sufre Golpeado.",
  "{cond} bursts on {name}: it deals Harm.": "{cond} estalla en {name}: le causa Daño.",
  "{name}'s unspent Charge ({n}) discharges as a Complication.": "La Carga sin gastar de {name} ({n}) se descarga como Complicación.",
  "{cond} on {name} ends.": "{cond} termina en {name}.",
  "The scene ends": "La escena termina",
  "End of Exchange {n}": "Fin del Intercambio {n}",
  "Other condition": "Otra condición",
  "Add a condition to {name}": "Añadir una condición a {name}",
  "Stunned": "Aturdido",
  "Stacks": "Acumulaciones",
  "Lasts (Exchanges)": "Dura (Intercambios)",
  "default": "por defecto",
  "Note": "Nota",
  "At the end of each Exchange the target takes Hurt, until it is put out.": "Al final de cada Intercambio el objetivo sufre Golpeado, hasta que lo apaguen.",
  "Each time the target spends E.G.O. or acts under strain, it takes Hurt. It stays until treated.": "Cada vez que el objetivo gasta E.G.O. o actúa bajo presión, sufre Golpeado. Dura hasta que lo traten.",
  "A delayed hit: it bursts for Harm at the end of the next Exchange, or earlier on a trigger.": "Un golpe retardado: estalla como Daño al final del siguiente Intercambio, o antes si salta un detonante.",
  "Each Rupture adds +1 Harm to the next hit on the target, then fades.": "Cada Ruptura añade +1 de Daño al siguiente golpe contra el objetivo, y luego se disipa.",
  "Each stack removes a die from the target's next roll, to a maximum of -3.": "Cada acumulación quita un dado a la siguiente tirada del objetivo, hasta un máximo de -3.",
  "Each Poise adds +1 die to your next Pride roll. A Failure spends it all.": "Cada Aplomo suma +1 dado a tu siguiente tirada de Orgullo. Un Fallo lo gasta todo.",
  "Spend Charge to add dice or Harm. Unspent Charge discharges as a Complication at the end of the scene.": "Gasta Carga para sumar dados o Daño. La Carga sin gastar se descarga como Complicación al final de la escena.",
  "A condition of your own.": "Una condición propia.",
  "Sinking: -{n} dice on this roll (applied automatically; it is used up).": "Hundimiento: -{n} dados en esta tirada (se aplica solo; se gasta).",
  "Poise: +{n} dice if you tag Pride (a Failure spends it all).": "Aplomo: +{n} dados si marcas Orgullo (un Fallo lo gasta todo).",
  " (Sinking: -{n} dice to them)": " (Hundimiento: -{n} dados para él)",
  "Sinking:": "Hundimiento:",
  "-{n} dice on this roll. It is used up.": "-{n} dados en esta tirada. Se gasta.",
  "Poise:": "Aplomo:",
  "+{n} dice on this Pride roll. A Failure spends it all.": "+{n} dados en esta tirada de Orgullo. Un Fallo lo gasta todo.",
  "{name} is Sinking:": "{name} se hunde:",
  "-{n} dice on their roll. It is used up.": "-{n} dados en su tirada. Se gasta.",
  "Sinking -{n}": "Hundimiento -{n}",
  "{name} takes Hurt: Harm is now {harm}.": "{name} sufre Golpeado: el Daño ahora es {harm}.",
  "That combatant is no longer in the order.": "Ese combatiente ya no está en el orden.",
  "No Hurt is waiting for {name}.": "No hay Golpeado pendiente para {name}.",
  "Apply Hurt": "Aplicar Golpeado",
  "{name} has no sheet here. Mark the Harm yourself.": "{name} no tiene ficha aquí. Anota el Daño tú mismo.",
  "Could not reach {name}'s player.": "No se pudo contactar con el jugador de {name}.",
  "{name} takes Hurt.": "{name} sufre Golpeado.",
  "Harm becomes at least Hurt": "El Daño pasa a ser al menos Golpeado",
  "{name} burns, but Harm is already {harm}: no change.": "{name} arde, pero el Daño ya es {harm}: sin cambios.",
  "The same words in {lang} (for the Voice and the Verdict)": "Las mismas palabras en {lang} (para la Voz y el Veredicto)",
  "The words above are written in": "Las palabras de arriba están escritas en",
  "Optional. Cards that quote these words then read in each player's language.": "Opcional. Las tarjetas que citan estas palabras se leen entonces en el idioma de cada jugador.",
  "The same Acceptance in {lang} (optional; if empty, the same words show to everyone)": "La misma Aceptación en {lang} (opcional; si está vacía, todos ven las mismas palabras)",
  "Click the map to point everyone to a spot": "Pulsa el mapa para señalar un punto a todos",
  "Ping": "Señalar",
  "Also centre everyone's view on the spot": "Centra también la vista de todos en ese punto",
  "Look here": "Mirad aquí",
  "The GM pinged the map": "El DJ ha señalado el mapa",
  "{name} pinged the map": "{name} ha señalado el mapa",
  "Red": "Rojo", "Orange": "Naranja", "Gold": "Dorado", "Green": "Verde", "Teal": "Turquesa", "Blue": "Azul", "Purple": "Morado", "White": "Blanco"
};
