/** Spanish for the guided character builder (Part III of the manual). */
export const CREATION_ES = {
  "Who is this?": "¿Quién es?",
  "Where from, and how do you survive?": "¿De dónde viene y cómo sobrevive?",
  "The people and the cause": "Las personas y la causa",
  "Your Wound": "Tu Herida",
  "What you want, and what trips you": "Lo que quieres y lo que te hace tropezar",
  "Attributes": "Atributos",
  "Skills": "Habilidades",
  "What you carry": "Lo que llevas",
  "Review": "Revisión",
  "Fixer (any grade)": "Agente (cualquier Grado)",
  "Wing Researcher": "Investigador/a de Ala",
  "Office Employee": "Empleado de Oficina",
  "Backstreets Survivor": "Superviviente de los Callejones",
  "Syndicate Member": "Miembro de un Sindicato",
  "Backstreets Medic (unlicensed)": "Médica de los Callejones (sin licencia)",
  "Wing Security": "Seguridad de Ala",
  "Independent Investigator": "Investigador/a Independiente",
  "Combat or Stealth": "Combate o Sigilo",
  "Medicine or Investigation": "Medicina o Investigación",
  "Stealth, Medicine or Technology": "Sigilo, Medicina o Tecnología",
  "Deception or Persuasion": "Engaño o Persuasión",
  "{name} is ready. Check the sheet and press Export to keep a copy.": "{name} está listo. Revisa la ficha y pulsa Exportar para guardar una copia.",
  "Not filled in yet: {field}": "Todavía sin rellenar: {field}",
  "Relationship": "Relación",
  "Give the character a name.": "Ponle un nombre al personaje.",
  "Pick exactly three Skills for the Occupation.": "Elige exactamente tres Habilidades para la Ocupación.",
  "{n} Attribute points left to spend.": "Quedan {n} puntos de Atributo por gastar.",
  "Too many points in an Attribute.": "Demasiados puntos en un Atributo.",
  "{n} Skill points left to spend.": "Quedan {n} puntos de Habilidad por gastar.",
  "A Skill is above 3, or too many points are spent.": "Una Habilidad pasa de 3, o se han gastado demasiados puntos.",
  "{n} Resonance points left to spend.": "Quedan {n} puntos de Resonancia por gastar.",
  "Too many Resonance points.": "Demasiados puntos de Resonancia.",
  "Attuned gear needs a Sin.": "El equipo sintonizado necesita un Pecado.",
  "Build a character in order: later steps rest on earlier ones. This is Part III of the manual.": "Construye el personaje en orden: los pasos posteriores se apoyan en los anteriores. Es la Parte III del manual.",
  "One line joining who you are and what you do.": "Una línea que une quién eres y a qué te dedicas.",
  "A Backstreets medic who used to work Wing security.": "Una médica de los Callejones que antes trabajó en seguridad de un Ala.",
  "A short phrase about yourself, not a class. Your E.G.O. Manifestation and Distortion will relate back to it.": "Una frase corta sobre ti, no una clase. Tu Manifestación de E.G.O. y tu Distorsión se relacionarán con ella.",
  "The one who fixes people, not machines.": "La que arregla personas, no máquinas.",
  "Where you are from. It colours your starting Bonds and may give one free Skill point, if your GM allows it.": "De dónde vienes. Da color a tus Vínculos iniciales y puede darte un punto de Habilidad gratis, si tu DJ lo permite.",
  "Raised in the Row": "Criada en la Fila",
  "Free Skill point from the Background (if your GM allows)": "Punto de Habilidad gratis del Trasfondo (si tu DJ lo permite)",
  "My GM also gives a minor Bond from the Background (Strength 1)": "Mi DJ también da un Vínculo menor del Trasfondo (Fuerza 1)",
  "Occupation package (a template: change the Skills if you like)": "Paquete de Ocupación (una plantilla: cambia las Habilidades si quieres)",
  "Build my own": "Crear el mío",
  "How you survive.": "Cómo sobrevives.",
  "Backstreets Medic (unlicensed)": "Médica de los Callejones (sin licencia)",
  "of 3 package Skills (each starts at 2)": "de 3 Habilidades del paquete (cada una empieza en 2)",
  "The manual offers: {x}": "El manual ofrece: {x}",
  "A Wing, the Association, a Syndicate, a mutual-aid network, or none. It gives you a starting Bond (Strength 1).": "Un Ala, la Asociación, un Sindicato, una red de ayuda mutua, o ninguna. Te da un Vínculo inicial (Fuerza 1).",
  "Mutual-aid network (Threadmill Row clinic)": "Red de ayuda mutua (clínica de la Fila Threadmill)",
  "What that Bond is": "Qué clase de Vínculo es",
  "One person who matters to you. It gives you a Bond (Strength 2) of a kind you choose.": "Una persona que te importa. Te da un Vínculo (Fuerza 2) del tipo que elijas.",
  "Old Tabbi, who runs the Row clinic": "La vieja Tabbi, que lleva la clínica de la Fila",
  "One belief, stated so that it can bend under real pressure. It has no number; the GM can bring it up like a Vice.": "Una creencia, formulada de modo que pueda doblegarse bajo presión real. No tiene número; el DJ puede sacarla a colación como un Vicio.",
  "Everyone gets one honest chance to be helped.": "Todo el mundo merece una oportunidad honesta de recibir ayuda.",
  "Answer three questions together, as one thing: what happened to you, what you are afraid of because of it, and what line you will never cross again because of it. Write all three in one sitting.": "Responde tres preguntas juntas, como una sola cosa: qué te pasó, a qué le tienes miedo por ello y qué línea no volverás a cruzar por ello. Escribe las tres de una vez.",
  "Burden: what happened": "Carga: lo que pasó",
  "A concrete past event, written so it can trigger again. It becomes your starting Trauma. Write only as much as you want on the table.": "Un suceso concreto del pasado, escrito de modo que pueda volver a dispararse. Se convierte en tu Trauma inicial. Escribe solo lo que quieras poner sobre la mesa.",
  "A Wing guard bled out in my arms after I waited for a supervisor's sign-off.": "Un guardia del Ala se desangró en mis brazos mientras esperaba la firma de un supervisor.",
  "Specific enough to name: not \"dying\" but \"dying without anyone knowing what happened to me\".": "Lo bastante concreto para nombrarlo: no «morir», sino «morir sin que nadie sepa lo que me pasó».",
  "Dying without anyone knowing what happened to me.": "Morir sin que nadie sepa lo que me pasó.",
  "Personal, not a setting-wide taboo. This is the fault line the Hail Mary keys off.": "Personal, no un tabú general del mundo. Es la línea de falla de la que depende el Último Recurso.",
  "I won't let someone die on my table because I hesitated.": "No dejaré que alguien muera en mi mesa porque dudé.",
  "What does that Wound feel like?": "¿Cómo se siente esa Herida?",
  "Resonance points left": "Puntos de Resonancia por gastar",
  "Up to {max} in any one Sin. Your highest is your Alignment.": "Hasta {max} en un mismo Pecado. Tu más alto es tu Alineamiento.",
  "tied with {x}; the first on the sheet counts": "empatado con {x}; cuenta el primero de la ficha",
  "A concrete, pursuable want the GM can put pressure on.": "Algo concreto y perseguible que quieres, sobre lo que el DJ puede presionar.",
  "Open a real clinic with a door that locks and a license on the wall.": "Abrir una clínica de verdad, con una puerta que cierre y una licencia en la pared.",
  "A specific, recurring weakness. The GM may invoke it to add a complication, and you regain 1 E.G.O. when it does (once per scene).": "Una debilidad específica y recurrente. El DJ puede invocarla para añadir una complicación, y recuperas 1 E.G.O. cuando lo hace (una vez por escena).",
  "Can't say no to a patient, even when it's obviously a trap.": "No puede decir que no a un paciente, aunque sea obviamente una trampa.",
  "The question your whole story should eventually answer.": "La pregunta que tu historia entera debería acabar respondiendo.",
  "Is a clean conscience something the City lets you keep?": "¿Es una conciencia limpia algo que la Ciudad te deja conservar?",
  "All four start at 1. Spend 6 more points, up to 4 in any one (5 is earned in play).": "Los cuatro empiezan en 1. Gasta 6 puntos más, hasta 4 en cada uno (el 5 se gana jugando).",
  "Attribute points left": "Puntos de Atributo por gastar",
  "Your E.G.O. maximum is your Resolve: {n}": "Tu máximo de E.G.O. es tu Voluntad: {n}",
  "Your package Skills start at 2. Spend 7 more points freely, with no Skill above 3.": "Las Habilidades de tu paquete empiezan en 2. Gasta 7 puntos más a tu gusto, sin que ninguna pase de 3.",
  "Skill points left": "Puntos de Habilidad por gastar",
  "package": "paquete",
  "You start with Resources 2 and one piece of gear of Cost 2 or less. It may be attuned to a Sin, so you begin with one already in hand.": "Empiezas con Recursos 2 y una pieza de equipo de Coste 2 o menos. Puede estar sintonizada con un Pecado, así que empiezas con uno ya en la mano.",
  "Leave empty for none.": "Déjalo vacío si no llevas nada.",
  "Ember Knife": "Cuchillo de Brasas",
  "Attuned to": "Sintonizado con",
  "(a Sin)": "(un Pecado)",
  "What it does": "Qué hace",
  "A blade that never quite cools.": "Una hoja que nunca se enfría del todo.",
  "Still open": "Aún pendiente",
  "You can create the character now and finish the rest on the sheet.": "Puedes crear el personaje ahora y terminar el resto en la ficha.",
  "Everything the manual asks for is done.": "Todo lo que pide el manual está hecho.",
  "Skip the guide: blank sheet": "Saltar la guía: ficha en blanco",
  "Back": "Atrás",
  "Create the character": "Crear el personaje",
  "Next": "Siguiente"
};
