/**
 * Spanish strings. The key is the English text exactly as it appears in the code and templates; keep {placeholders}
 * and <b> tags identical. Terminology follows the Spanish manual (Último Recurso, Punto de Quiebre, Vínculo, ...).
 */
export const ES = {
  // ---- labels (config) ----
  "Wrath": "Ira", "Lust": "Lujuria", "Sloth": "Pereza", "Gluttony": "Gula", "Gloom": "Melancolía", "Pride": "Orgullo", "Envy": "Envidia",
  "Combat": "Combate", "Athletics": "Atletismo", "Stealth": "Sigilo", "Investigation": "Investigación", "Technology": "Tecnología",
  "Medicine": "Medicina", "Persuasion": "Persuasión", "Deception": "Engaño", "Empathy": "Empatía", "Streetwise": "Callejeo",
  "Corporate Knowledge": "Conocimiento Corporativo", "Fixer Knowledge": "Conocimiento de Agentes",
  "Body": "Cuerpo", "Mind": "Mente", "Presence": "Presencia", "Resolve": "Voluntad",
  "Unhurt": "Ileso", "Hurt": "Golpeado", "Injured (-1)": "Herido (−1)", "Wounded (-2)": "Malherido (−2)", "Maimed / Dying": "Mutilado / Moribundo",
  "Mundane": "Mundano", "Weapon": "Arma", "Suit": "Traje", "Tool": "Herramienta", "Charm": "Amuleto",
  "Trust": "Confianza", "Fear": "Miedo", "Debt": "Deuda", "Affection": "Afecto", "Obligation": "Obligación", "Hatred": "Odio",
  "Burn": "Quemadura", "Bleed": "Sangrado", "Tremor": "Temblor", "Rupture": "Ruptura", "Sinking": "Hundimiento", "Poise": "Aplomo", "Charge": "Carga",
  "Safehouse": "Refugio", "Getaway": "Vía de escape", "Workshop contact": "Contacto en un Taller", "Informant": "Informante", "Clinic": "Clínica", "Cover": "Tapadera",

  // ---- the Sins: complications and urges ----
  "Collateral: something breaks, someone who wasn't the target is hurt, or a line is crossed in public.": "Daño colateral: algo se rompe, alguien que no era el objetivo sale herido, o se cruza una línea en público.",
  "Lashes out first, hardest, at the nearest target.": "Golpea primero, con más fuerza, al objetivo más cercano.",
  "Attachment: a promise made in the moment, a new person pulled into the problem, or a Bond strained by what you offered.": "Apego: una promesa hecha en el momento, una persona nueva arrastrada al problema, o un Vínculo tensado por lo que ofreciste.",
  "Reaches for someone or something to cling to; overpromises.": "Se aferra a alguien o algo; promete de más.",
  "Delay: the window closes, time is lost, an opportunity quietly passes.": "Demora: la ventana se cierra, se pierde tiempo, una oportunidad pasa en silencio.",
  "Stops. Waits. Defers the choice and lets someone else make it.": "Se detiene. Espera. Aplaza la decisión y deja que la tome otro.",
  "Excess: you took too much; it leaves a trace, a debt, a mess, or a rival who noticed.": "Exceso: tomaste demasiado; deja un rastro, una deuda, un desastre, o un rival que se fijó.",
  "Takes more than needed and consumes it.": "Toma más de lo necesario y lo consume.",
  "Weight: your sorrow is contagious; an ally nearby takes -1 die on their next roll.": "Peso: tu pena es contagiosa; un aliado cercano sufre −1 dado en su siguiente tirada.",
  "Collapses inward: takes the blame, mourns aloud, drags others down.": "Se derrumba hacia dentro: asume la culpa, llora en voz alta, arrastra a los demás.",
  "Face: standing is lost, a witness saw you stumble, or someone now has something over your reputation.": "Cara: se pierde reputación, un testigo te vio tropezar, o alguien tiene ahora algo contra tu buen nombre.",
  "Refuses help, doubles down, performs for the room.": "Rechaza la ayuda, redobla la apuesta, actúa para la sala.",
  "Rivalry: someone becomes your rival, or covets what you have.": "Rivalidad: alguien se vuelve tu rival, o codicia lo que tienes.",
  "Copies, undercuts, sabotages whoever is better.": "Copia, socava, sabotea a quien es mejor.",

  // ---- Signature Techniques ----
  "Rampage": "Arrebato", "Hook": "Anzuelo", "Unmoved": "Inmóvil", "Devour": "Devorar", "Sorrow's Weight": "Peso de la Pena", "Unbowed": "Sin Doblegar", "Borrowed Face": "Rostro Prestado",
  "After a Wrath-tagged Success in a fight, make a second Wrath-tagged attack on a different target at -1 die. If either roll shows a 1, an unintended person takes Hurt.": "Tras un Éxito etiquetado con Ira en una pelea, haz un segundo ataque etiquetado con Ira contra otro objetivo con −1 dado. Si cualquiera de las dos tiradas muestra un 1, una persona ajena sufre Golpeado.",
  "On a Success on a Lust-tagged social roll, the target holds a 1-point Bond toward you until the scene ends, which you may spend once.": "Con un Éxito en una tirada social etiquetada con Lujuria, el objetivo siente un Vínculo de 1 punto hacia ti hasta que acabe la escena, que puedes gastar una vez.",
  "Once per scene, do nothing as your Exchange action: until your next action, attacks and pressure against you are rolled at -2 dice and you can't be Helped.": "Una vez por escena, no hagas nada como tu acción del Intercambio: hasta tu siguiente acción, los ataques y la presión contra ti se tiran con −2 dados y no puedes recibir Ayuda.",
  "Once per scene, when you inflict Harm or win a Social Conflict, regain 1 E.G.O. or take something. You owe the scene a cost.": "Una vez por escena, cuando infliges Daño o ganas un Conflicto Social, recupera 1 E.G.O. o toma algo. Le debes a la escena un coste.",
  "On a Success on a Gloom-tagged roll, the target takes -2 dice on their next roll this scene.": "Con un Éxito en una tirada etiquetada con Melancolía, el objetivo sufre −2 dados en su siguiente tirada de la escena.",
  "Once per scene, after rolling, reroll up to three dice that didn't succeed. If the reroll still fails, take a Complication.": "Una vez por escena, tras tirar, vuelve a tirar hasta tres dados que no fueron Éxito. Si aun así falla, sufres una Complicación.",
  "Once per scene, after your opponent tags a Sin, tag the same one yourself: the matchup is neutral and you add +1 die.": "Una vez por escena, después de que tu oponente etiquete un Pecado, etiqueta tú el mismo: el enfrentamiento es neutral y sumas +1 dado.",

  // ---- the Voice and the Verdict ----
  "You are going to let them get away with it again.": "Vas a dejar que se salgan con la suya otra vez.",
  "Hold on to them. Do not let them go.": "Aférrate a ellos. No los dejes ir.",
  "Wait. Do not choose. Someone else will.": "Espera. No elijas. Ya lo hará otro.",
  "More. You will never have enough.": "Más. Nunca tendrás suficiente.",
  "It is your fault. It was always your fault.": "Es culpa tuya. Siempre fue culpa tuya.",
  "Do not let them see you stumble.": "No dejes que te vean tropezar.",
  "They have what you lost.": "Ellos tienen lo que tú perdiste.",
  "lashes out": "golpea", "withdraws or sabotages quietly": "se retira o sabotea en silencio", "performs or provokes": "actúa o provoca", "refuses and digs in": "se niega y se atrinchera",
  "You know how this ends.": "Sabes cómo acaba esto.",
  "You are afraid of this, and it is already true: \"{fear}\"": "Tienes miedo de esto, y ya es verdad: \"{fear}\"",
  "You remember. {burden}": "Lo recuerdas. {burden}",
  "Empty: the Voice is loud now. A Flashpoint on every 1. When it hits, they {shape} (their highest Attribute).": "Vacío: la Voz suena fuerte ahora. Un Punto de Quiebre con cada 1. Cuando llega, el personaje {shape} (su Atributo más alto).",
  "Unsteady: the Voice is soft, just under their thoughts. The first 1 each scene is a Flashpoint; they {shape}.": "Inestable: la Voz es suave, justo bajo sus pensamientos. El primer 1 de cada escena es un Punto de Quiebre; el personaje {shape}.",
  "You remember it. {burden} People like you always let it happen.": "Lo recuerdas. {burden} La gente como tú siempre deja que ocurra.",
  "You swore: \"{boundary}\" Say it again, and watch yourself break it.": "Lo juraste: \"{boundary}\" Dilo otra vez, y mírate romperlo.",
  "The Verdict": "El Veredicto", "Acceptance.": "Aceptación.", "No Acceptance yet.": "Aún no hay Aceptación.", "The answer has not been spoken.": "La respuesta no se ha pronunciado.", "The Voice": "La Voz",

  // ---- rules text that reaches the screen ----
  "Critical Failure": "Fallo Crítico", "Failure": "Fallo", "Partial": "Parcial", "Success": "Éxito", "Critical Success": "Éxito Crítico",
  "E.G.O. Manifestation, clean. E.G.O. refills to 1. Stress +1.": "Manifestación de E.G.O., limpia. El E.G.O. se rellena a 1. Estrés +1.",
  "E.G.O. Manifestation, at a cost: a Trauma marked or a Boundary bent. Stress +1.": "Manifestación de E.G.O., con coste: un Trauma marcado o un Límite doblado. Estrés +1.",
  "Partial Distortion: genuinely transformed and monstrous, the player keeps the wheel. Stress +2.": "Distorsión Parcial: realmente transformado y monstruoso, el jugador conserva el control. Estrés +2.",
  "Complete Distortion: the self is pushed out. Lasts until the fiction brings them back. Stress +2.": "Distorsión Completa: el yo queda desplazado. Dura hasta que la ficción lo traiga de vuelta. Estrés +2.",
  "Complete Distortion, already severe: death or permanence are live options. Stress +2.": "Distorsión Completa, ya grave: la muerte o lo permanente son opciones reales. Estrés +2.",
  "That Sin is Strained by a Scar until the Scar Heals.": "Ese Pecado está Tensado por una Cicatriz hasta que la Cicatriz Sane.",
  "Signature Techniques need Resonance 2 or more.": "Las Técnicas Distintivas necesitan Resonancia 2 o más.",
  "Already used {used} of {max} this scene.": "Ya usada {used} de {max} veces esta escena.",

  // ---- roll dialog and chat cards ----
  "{n} Success": "{n} Éxito", "{n} Successes": "{n} Éxitos",
  "None": "Ninguno", "No Bond": "Sin Vínculo", "No tag": "Sin etiqueta", "None / untagged": "Ninguno / sin etiqueta",
  "Target: {name}": "Objetivo: {name}",
  " (Unmoved: -2 dice to your roll, no Help)": " (Inmóvil: −2 dados a tu tirada, sin Ayuda)",
  " (weighed down {n})": " (abrumado {n})",
  "Rampage armed: this roll is the second attack, tagged Wrath at -1 die.": "Arrebato preparado: esta tirada es el segundo ataque, etiquetado con Ira con −1 dado.",
  "Sorrow's Weight: {n} dice on this roll.": "Peso de la Pena: {n} dados en esta tirada.",
  "Under {sin}: Fit applies.": "Bajo {sin}: se aplica el Encaje.",
  "Attribute": "Atributo", "Skill": "Habilidad", "(none)": "(ninguna)", "Difficulty": "Dificultad", "Opposition dice": "Dados de oposición",
  "0 = roll against the Difficulty": "0 = tirar contra la Dificultad",
  "Tag a Sin": "Etiquetar un Pecado", "Their Sin": "Su Pecado", "Roll is": "La tirada es", "an attack": "un ataque", "a defense": "una defensa", "something else": "otra cosa",
  "Attuned gear": "Equipo sintonizado", "E.G.O. dice (have {n})": "Dados de E.G.O. (tienes {n})", "Help dice": "Dados de Ayuda", "Other +/-": "Otros +/−",
  "Spend a Bond (+1 die)": "Gastar un Vínculo (+1 dado)",
  "Borrowed Face: copy their Sin tag (+1 die, matchup neutral)": "Rostro Prestado: copiar su etiqueta de Pecado (+1 dado, enfrentamiento neutro)",
  "Roll: {name}": "Tirada: {name}", "Roll": "Tirar",
  "Rampage:": "Arrebato:", "the second attack, at -1 die.": "el segundo ataque, con −1 dado.",
  "{name} is Unmoved:": "{name} está Inmóvil:", "-2 dice to this roll and no Help.": "−2 dados a esta tirada y sin Ayuda.",
  "Borrowed Face:": "Rostro Prestado:", "you copy {sin}. The matchup is neutral and you add +1 die.": "copias {sin}. El enfrentamiento es neutral y sumas +1 dado.",
  "Sorrow's Weight:": "Peso de la Pena:", "{n} dice on this roll.": "{n} dados en esta tirada.",
  "{name} is weighed down:": "{name} está abrumado:", "{n} dice on their roll.": "{n} dados en su tirada.",
  "Unbowed": "Sin Doblegar",
  "{name} is Pride-rated. Use <b>Unbowed</b> to reroll up to three dice that didn't succeed? If the reroll still fails, you take a Complication. (Once per scene, twice at rating 4.)": "{name} tiene Orgullo. ¿Usar <b>Sin Doblegar</b> para volver a tirar hasta tres dados que no fueron Éxito? Si aun así falla, sufres una Complicación. (Una vez por escena, dos con puntuación 4.)",
  "Unbowed:": "Sin Doblegar:", "rerolled {n} dice.": "se repitieron {n} dados.", "It still fails:": "Sigue fallando:", "take a Complication": "sufre una Complicación",
  "Rampage collateral:": "Daño colateral del Arrebato:", "a 1 showed on one of the two attacks, so an unintended person takes Hurt.": "salió un 1 en uno de los dos ataques, así que una persona ajena sufre Golpeado.",
  "Harm": "Daño", "Tag {sin}: matchup {m}, Fit {f}": "Etiqueta {sin}: enfrentamiento {m}, Encaje {f}", "(borrowed, as rating 2)": "(prestado, como puntuación 2)", ", Boon {b}": ", Bono {b}",
  "dice": "dados", "Help": "Ayuda", "Bond": "Vínculo", "other": "otros", "effects": "efectos", "Pool": "Reserva", "vs": "contra",
  "{n} opposing dice": "{n} dados de oposición", "Difficulty {n}": "Dificultad {n}", "target {name}": "objetivo {name}",
  "{n} Complications": "{n} Complicaciones", "1 Complication": "1 Complicación", "a concrete cost the GM chooses.": "un coste concreto que elige el DJ.",
  "Flashpoint:": "Punto de Quiebre:",
  "the Vice or {sin}'s Urge ({urge}) takes the wheel for a beat.": "el Vicio o el Impulso de {sin} ({urge}) toma el control un momento.",
  "the Vice takes the wheel for a beat.": "el Vicio toma el control un momento.",
  "Shape (highest Attribute, {attr}): {shape}.": "Forma (Atributo más alto, {attr}): {shape}.",
  "Pull:": "Tirón:", "{gear} provokes {sin}: {text} (Wear {w}/3)": "{gear} provoca a {sin}: {text} (Desgaste {w}/3)",

  // ---- Hail Mary ----
  "The Voice becomes the <b>Verdict</b>: what the Wound has always said about this character, in the words of their Fear and in {sin}'s voice. The GM speaks it (edit it freely). The player answers with the <b>Acceptance</b>: who the character is underneath.": "La Voz se convierte en el <b>Veredicto</b>: lo que la Herida siempre ha dicho de este personaje, con las palabras de su Miedo y con la voz de {sin}. Lo pronuncia el DJ (edítalo con libertad). El jugador responde con la <b>Aceptación</b>: quién es el personaje por debajo.",
  "their Sin": "su Pecado", "Verdict": "Veredicto", "Other starting points:": "Otros puntos de partida:",
  "Acceptance (the player's answer, in their own words)": "Aceptación (la respuesta del jugador, con sus propias palabras)",
  "Base Difficulty": "Dificultad base",
  "A sincere Desire is on the line (the Boundary now contradicts it)": "Hay un Deseo sincero en juego (el Límite ahora lo contradice)",
  "Dig deep (spend all E.G.O., +1 Difficulty; needs 2+)": "Cavar hondo (gastar todo el E.G.O., +1 Dificultad; necesita 2+)",
  "Drastic moment (+1 Difficulty)": "Momento drástico (+1 Dificultad)",
  "Spend a Bond for +1 die": "Gastar un Vínculo por +1 dado",
  "Leave the Acceptance empty if the player can't or won't say it: a Success then becomes a Partial Distortion.": "Deja la Aceptación vacía si el jugador no puede o no quiere decirla: un Éxito se convierte entonces en una Distorsión Parcial.",
  "Hail Mary: {name}": "Último Recurso: {name}", "Speak the Verdict and roll": "Pronunciar el Veredicto y tirar",
  "Digging deep needs at least 2 E.G.O.": "Cavar hondo necesita al menos 2 E.G.O.",
  "No Acceptance:": "Sin Aceptación:", "the Success becomes a Partial Distortion.": "el Éxito se convierte en una Distorsión Parcial.",
  "The denial holds: the Verdict is answered.": "La negación aguanta: el Veredicto queda respondido.",
  "Half-believing the Verdict.": "Creyendo a medias el Veredicto.",
  "The Verdict is louder than they are.": "El Veredicto suena más fuerte que él.",
  "no sincere Desire is on the line, so this may not be a Hail Mary moment (Part IV §4). It can't be a tragedy the character already thought they deserved.": "no hay un Deseo sincero en juego, así que puede que este no sea un momento de Último Recurso (Parte IV §4). No puede ser una tragedia que el personaje ya creyera merecer.",
  "Hail Mary": "Último Recurso", "broken": "rotos", "vs Difficulty {n}": "contra Dificultad {n}", "Fraying": "Quebradizo",
  "digging deep": "cavando hondo", "drastic moment": "momento drástico", "Stress +{n} applied.": "Estrés +{n} aplicado.", "E.G.O. spent.": "E.G.O. gastado.",
  "Grade": "Grado", "group": "grupo", "{a} less Sorrow's Weight {b}": "{a} menos Peso de la Pena {b}", "rating": "puntuación",

  // ---- downtime ----
  "Project Moon: use the Import Pregens button in the Actors tab to add Wren, Dax, Lena and Tomas.": "Project Moon: usa el botón Importar Prefabricados en la pestaña de Actores para añadir a Wren, Dax, Lena y Tomas.",
  "Import Pregens": "Importar Prefabricados",
  "No characters to run a downtime phase for.": "No hay personajes para la fase de tiempo libre.",
  "Each character pays <b>1 Resources</b> of upkeep (short means Stress +1). Rest returns E.G.O. up to {n}.": "Cada personaje paga <b>1 Recurso</b> de mantenimiento (si no llega, Estrés +1). El descanso devuelve E.G.O. hasta {n}.",
  "Character": "Personaje", "Resources": "Recursos", "Spent gear": "Equipo agotado", "Rest": "Descanso", "Repair (1 each)": "Reparar (1 cada uno)",
  "The Fund pays 1 to keep {n} Assets up.": "El Fondo paga 1 para mantener {n} Bienes.",
  "Downtime phase": "Fase de tiempo libre", "Run it": "Ejecutar",
  "could not pay upkeep, <b>Stress +1</b>": "no pudo pagar el mantenimiento, <b>Estrés +1</b>",
  "paid {paid} (Resources {from} to {to})": "pagó {paid} (Recursos {from} a {to})",
  "repaired {n} pieces of gear": "reparó {n} piezas de equipo",
  "rested <b>+{n} E.G.O.</b>": "descansó <b>+{n} E.G.O.</b>",
  "<b>Fund</b> paid {pays} to keep {n} Assets up (now {left}).": "El <b>Fondo</b> pagó {pays} para mantener {n} Bienes (ahora {left}).",
  "Fund no longer needed for upkeep: the dormant Asset is back.": "El Fondo ya no hace falta para el mantenimiento: el Bien inactivo vuelve.",
  "The Fund can't keep the Assets up": "El Fondo no puede mantener los Bienes",
  "The Fund is empty. Which Asset goes dormant (the newest)?": "El Fondo está vacío. ¿Qué Bien queda inactivo (el más reciente)?",
  "Go dormant": "Dejar inactivo",
  "<b>Fund</b> could not pay: <b>{asset}</b> goes dormant until it can.": "El <b>Fondo</b> no pudo pagar: <b>{asset}</b> queda inactivo hasta que pueda.",
  "Imported: {names}": "Importados: {names}", "The pregenerated characters already exist.": "Los personajes prefabricados ya existen.",

  // ---- sheets: scene, drift, crew ----
  "New gear": "Equipo nuevo", "New Bond": "Vínculo nuevo", "New Trauma": "Trauma nuevo", "New item": "Objeto nuevo",
  "Empty": "Vacío", "Unsteady": "Inestable",
  "New scene: Flashpoint, Pull, techniques, Vice, refunds and scene effects reset; Riding ended; Hooks expire.": "Escena nueva: Punto de Quiebre, Tirón, técnicas, Vicio, reembolsos y efectos de escena reiniciados; Cabalgar termina; los Anzuelos caducan.",
  "You need Resonance 2 or more in a Sin to Ride it.": "Necesitas Resonancia 2 o más en un Pecado para Cabalgarlo.",
  "Drift": "Deriva", "No Sin leads by 8 or more tags. Clear the tally anyway?": "Ningún Pecado aventaja por 8 o más etiquetas. ¿Borrar la cuenta de todos modos?",
  "<b>{gain}</b> gains 1; <b>{lose}</b> loses 1. The tally is cleared.": "<b>{gain}</b> gana 1; <b>{lose}</b> pierde 1. Se borra la cuenta.",
  "Holding": "Resistiendo", "Breaking": "Cediendo", "Routed": "Derrotada", "any": "cualquiera",
  "Safehouse (3)": "Refugio (3)", "Recover up to 3 E.G.O. between Contracts": "Recupera hasta 3 E.G.O. entre Contratos",
  "Getaway (2)": "Vía de escape (2)", "Chases clear a segment on a win by 1": "En las persecuciones se quita un segmento al ganar por 1",
  "Workshop contact (2)": "Contacto en un Taller (2)", "Free repairs, -1 Cost once per phase": "Reparaciones gratis, −1 de Coste una vez por fase",
  "Informant (2)": "Informante (2)", "Preparation die is two dice": "El dado de preparación son dos dados",
  "Clinic (2)": "Clínica (2)", "Treatment rolls are one Difficulty lower": "Las tiradas de tratamiento tienen una Dificultad menos",
  "Cover (2)": "Tapadera (2)", "The first Heat segment each Contract is not filled": "El primer segmento de Presión de cada Contrato no se llena",
  "There are no characters in this world yet.": "Todavía no hay personajes en este mundo.", "Crew members": "Miembros del equipo",
  "With nobody ticked, the crew is every character in the world.": "Si no marcas a nadie, el equipo son todos los personajes del mundo.",
  "Save": "Guardar", "New Clock": "Reloj nuevo", "Name": "Nombre", "Kurokumo Heat": "Presión de Kurokumo", "Segments": "Segmentos", "Add": "Añadir", "Clock": "Reloj",
  "Clock full: {name}": "Reloj lleno: {name}",
  "Something concrete happens: an audit, a visit, a contract pulled. Never vague.": "Ocurre algo concreto: una auditoría, una visita, un contrato retirado. Nunca vago.",
  "Ledger entry": "Entrada del registro", "Client": "Cliente", "Risk": "Riesgo", "Report": "Informe", "Honest": "Honesto", "Falsified": "Falsificado",
  "Pay the members their Resources now": "Pagar ya sus Recursos a los miembros",
  "Each member is paid {n} Resources (capped at 5).": "Cada miembro cobra {n} Recursos (tope 5).",
  "A falsified Report opens a Heat Clock (4) on the Association. Add it to the crew's Clocks.": "Un Informe falsificado abre un Reloj de Presión (4) en la Asociación. Añádelo a los Relojes del equipo.",

  // ---- techniques ----
  "<b>{name}</b> follows a {sin}-tagged Success, and your last roll wasn't one. Use it anyway?": "<b>{name}</b> sigue a un Éxito etiquetado con {sin}, y tu última tirada no lo era. ¿Usarla de todos modos?",
  "Choose the target": "Elige el objetivo", "Target": "Objetivo",
  "Armed.": "Preparado.",
  "Your next roll is the second attack: tagged Wrath, at -1 die, and the dialog is preset for it. If either attack shows a 1, an unintended person takes Hurt.": "Tu próxima tirada es el segundo ataque: etiquetado con Ira, con −1 dado, y el diálogo ya viene preparado. Si cualquiera de los dos ataques muestra un 1, una persona ajena sufre Golpeado.",
  "Who is hooked": "A quién se engancha", "the target": "el objetivo", "Hooked: {who}": "Enganchado: {who}",
  "{who} holds a 1-point {bond} Bond toward you until the scene ends.": "{who} siente un Vínculo de {bond} de 1 punto hacia ti hasta que acabe la escena.",
  "It appears in your Bonds and in the roll dialog; spend it once like one of your own. The GM may veto if it crosses your Boundary.": "Aparece en tus Vínculos y en el diálogo de tirada; gástalo una vez como uno tuyo. El DJ puede vetarlo si cruza tu Límite.",
  "Unmoved is up": "Inmóvil está activo",
  "until your next action. Anyone targeting you with the roll dialog takes -2 dice and can't add Help dice. Rolling anything yourself ends it.": "hasta tu siguiente acción. Quien te tome como objetivo en el diálogo de tirada sufre −2 dados y no puede añadir dados de Ayuda. Tirar tú cualquier cosa lo termina.",
  "applied (refunds this scene: {n}/{cap}). You still owe the scene a cost: the GM names one.": "aplicado (reembolsos esta escena: {n}/{cap}). Aún le debes a la escena un coste: el DJ lo nombra.",
  "No E.G.O. to regain (full, or the {cap}-per-scene refund cap is reached). Take something instead: an object or a secret. You still owe the scene a cost.": "No hay E.G.O. que recuperar (está lleno, o se alcanzó el tope de {cap} reembolsos por escena). Toma algo en su lugar: un objeto o un secreto. Aún le debes a la escena un coste.",
  "No target chosen.": "No se eligió objetivo.",
  "takes -2 dice on their next roll this scene. It is applied automatically to their next roll, and to your roll if they are the target of it.": "sufre −2 dados en su siguiente tirada de la escena. Se aplica automáticamente a su próxima tirada, y a tu tirada si es el objetivo de ella.",
  "Unbowed is offered automatically after a roll that fails or comes up Partial: you may reroll up to three dice that didn't succeed, and if it still fails you take a Complication.": "Sin Doblegar se ofrece automáticamente tras una tirada que falla o sale Parcial: puedes volver a tirar hasta tres dados que no fueron Éxito, y si aun así falla sufres una Complicación.",
  "Borrowed Face appears as a checkbox in the roll dialog. Choose the opponent's Sin, tick it, and you tag the same Sin: the matchup is neutral and you add +1 die.": "Rostro Prestado aparece como casilla en el diálogo de tirada. Elige el Pecado del oponente, márcala, y etiquetas el mismo Pecado: el enfrentamiento es neutral y sumas +1 dado.",
  "This button spends nothing ({used}/{max} used this scene).": "Este botón no gasta nada ({used}/{max} usadas esta escena).",
  "{n}/{max} this scene": "{n}/{max} esta escena",
  "A Vice pays out E.G.O. at most once per scene.": "Un Vicio da E.G.O. como máximo una vez por escena.",
  "Vice invoked": "Vicio invocado", "<b>{vice}</b> creates a complication in the scene.": "<b>{vice}</b> crea una complicación en la escena.", "Their Vice": "Su Vicio",
  "+{n} E.G.O. (refunds this scene: {r}/{cap}).": "+{n} E.G.O. (reembolsos esta escena: {r}/{cap}).",
  "No E.G.O. gained (full, or the refund cap is reached).": "No se ganó E.G.O. (está lleno, o se alcanzó el tope de reembolsos).",

  // ---- sheet templates ----
  "Alignment": "Alineamiento", "Riding": "Cabalgando", "Rampage armed": "Arrebato preparado", "Weighed down": "Abrumado",
  "Stress": "Estrés", "New scene": "Escena nueva", "The Self": "El Yo", "Sins": "Pecados", "Gear and Bonds": "Equipo y Vínculos", "Notes": "Notas",
  "Concept": "Concepto", "Identity": "Identidad", "Occupation": "Ocupación", "Affiliation": "Afiliación", "Background": "Trasfondo",
  "Attributes": "Atributos", "Skills": "Habilidades", "click a name to roll": "pulsa un nombre para tirar", "Fit": "Encaje",
  "The Wound": "La Herida", "Burden": "Carga", "Boundary": "Límite", "Vice": "Vicio", "Invoke": "Invocar", "Desire": "Deseo", "Principle": "Principio", "Ambition": "Ambición",
  "Broken Boundaries": "Límites rotos", "Scars": "Cicatrices", "Traumas": "Traumas", "Edit": "Editar", "No Traumas yet.": "Aún no hay Traumas.",
  "Under a Sin (not Riding)": "Bajo un Pecado (sin Cabalgar)", "Strained by a Scar": "Tensado por una Cicatriz",
  "Sin": "Pecado", "Resonance": "Resonancia", "Tally": "Cuenta", "Wheel": "Rueda", "Fit (when Under)": "Encaje (estando Bajo)",
  "Strong": "Fuerte", "Weak": "Débil", "Ride": "Cabalgar", "this scene": "esta escena", "Strained": "Tensado", "Info": "Info", "Use": "Usar",
  "End-of-fourth-session Drift": "Deriva de fin de cuarta sesión",
  "Resources (0 to 5)": "Recursos (0 a 5)", "Downtime upkeep": "Mantenimiento de tiempo libre", "Gear": "Equipo", "Fine": "Fino", "Wear": "Desgaste", "Spent": "Agotado",
  "No gear.": "Sin equipo.", "Bonds": "Vínculos", "No Bonds.": "Sin Vínculos.",
  "Rest: +1 E.G.O.": "Descanso: +1 E.G.O.", "Reset Flashpoint and Pull, end Riding": "Reinicia Punto de Quiebre y Tirón, termina Cabalgar",
  "+1 E.G.O., once per scene, inside the refund cap": "+1 E.G.O., una vez por escena, dentro del tope de reembolsos",
  "Offered automatically during rolls; this button explains how": "Se ofrece automáticamente en las tiradas; este botón explica cómo",
  "Apply this technique": "Aplicar esta técnica", "Pay upkeep, repair Spent gear, rest": "Pagar mantenimiento, reparar equipo agotado, descansar",
  "Office Grade": "Grado de Oficina", "Highest Risk offered:": "Riesgo más alto ofrecido:", "Fractured": "Fracturado",
  "Office": "Oficina", "Association": "Asociación", "Function": "Función", "The Grind": "La Rutina", "Person Behind the Desk": "Persona Tras el Mostrador",
  "Associate Office (can't refuse assignments)": "Oficina Asociada (no puede rechazar asignaciones)",
  "Crew Bond": "Vínculo del Equipo", "Strength (0 = Fractured)": "Fuerza (0 = Fracturado)", "Fund (0 to 5)": "Fondo (0 a 5)",
  "Members": "Miembros", "Choose": "Elegir", "Run downtime upkeep": "Ejecutar mantenimiento de tiempo libre",
  "No characters in this world yet.": "Todavía no hay personajes en este mundo.",
  "Assets": "Bienes", "dormant": "inactivo",
  "With three or more Assets the Fund pays 1 each downtime phase to keep them up.": "Con tres o más Bienes, el Fondo paga 1 en cada fase de tiempo libre para mantenerlos.",
  "Heat and other Clocks": "Presión y otros Relojes", "Add Clock": "Añadir Reloj", "No Clocks yet.": "Aún no hay Relojes.",
  "Ledger": "Registro", "Add Contract": "Añadir Contrato", "Payment": "Pago", "Crew name": "Nombre del equipo",
  "Rolls {n} dice": "Tira {n} dados", "Difficulty to hit: {n}": "Dificultad para golpearlo: {n}", "Sin rating {n}": "Puntuación de Pecado {n}",
  "Roll its pool": "Tirar su reserva", "Threat Grade (9 to 1)": "Grado de Amenaza (9 a 1)",
  "A group (Threat track, +2 dice)": "Un grupo (rastro de Amenaza, +2 dados)", "Threat track": "Rastro de Amenaza",
  "The three things": "Las tres cosas", "Want": "Quiere", "Bond Hook": "Gancho de Vínculo", "One Detail": "Un Detalle",
  "Kind": "Tipo", "Fine (Cost 3, +2 if attuned at rating 3+)": "Fino (Coste 3, +2 si estás sintonizado con puntuación 3+)", "In use": "En uso",
  "Wear (3 = Spent)": "Desgaste (3 = Agotado)", "Cost": "Coste",
  "Weapon: +1 die on attacks tagged with its Sin. Suit: +1 die on defense. Tool: +1 die on a Favored Skill of the Sin. Charm: ignore the Sin's Complication once per scene. Below Resonance 2 you are borrowing it.": "Arma: +1 dado en los ataques etiquetados con su Pecado. Traje: +1 dado en defensa. Herramienta: +1 dado en una Habilidad Favorecida del Pecado. Amuleto: ignora la Complicación del Pecado una vez por escena. Por debajo de Resonancia 2 lo tomas prestado.",
  "Type": "Tipo", "Strength (1 to 3)": "Fuerza (1 a 3)", "With": "Con", "Trigger": "Detonante", "Reaction": "Reacción",
  "When it fires again: Stress +1 and a narrated reaction. Three times makes room for a second Boundary.": "Cuando vuelve a dispararse: Estrés +1 y una reacción narrada. Tres veces dan pie a un segundo Límite.",
  "Description": "Descripción"
};
