/** Spanish for the handouts. */
export const HANDOUT_ES = {
  "The GM shows a handout": "El DJ muestra un documento",
  "The GM shows you: {title}": "El DJ te muestra: {title}",
  "Handouts": "Documentos",
  "Untitled": "Sin título",
  "Marked as shown": "Marcado como mostrado",
  "Hidden": "Oculto",
  "View": "Ver",
  "Take back": "Retirar",
  "Handout": "Documento",
  "Contract": "Contrato",
  "No handouts yet. Add a note, a contract or a picture, then Show it to the table.": "Todavía no hay documentos. Añade una nota, un contrato o una imagen, y luego Muéstralo a la mesa.",
  "Nothing has been shown to you yet.": "Todavía no te han mostrado nada.",
  "Edit handout": "Editar documento",
  "New handout": "Documento nuevo",
  "Title": "Título",
  "Text (blank line = new paragraph; *italic*, **bold**)": "Texto (línea en blanco = párrafo nuevo; *cursiva*, **negrita**)",
  "A picture is attached.": "Hay una imagen adjunta.",
  "That is the most handouts this app keeps.": "Es el máximo de documentos que guarda esta aplicación.",
  "The job": "El trabajo",
  "Deadline": "Plazo",
  "Terms": "Condiciones",
  "This handout is only in {lang}.": "Este documento solo está en {lang}.",
  "Read in {lang}": "Leer en {lang}",
  "This version is in": "Esta versión está en",
  "Optional. Players who read the other language see this version.": "Opcional. Los jugadores que leen el otro idioma ven esta versión.",
  "Version in {lang} (optional)": "Versión en {lang} (opcional)",
  "Swap the two versions": "Intercambiar las dos versiones",
  "Shown only to {names}": "Mostrado solo a {names}",
  "Show it to some players only": "Mostrarlo solo a algunos jugadores",
  "Show to...": "Mostrar a...",
  "Nobody else is in the room yet.": "Todavía no hay nadie más en la sala.",
  "Who sees {title}?": "¿Quién ve {title}?",
  "Only the players you tick receive it and see it. Nobody else is told it exists.": "Solo los jugadores que marques lo reciben y lo ven. A nadie más se le avisa de que existe.",
  "Tick at least one player, or use Show for everyone.": "Marca al menos a un jugador, o usa Mostrar para todos.",
  "Shown privately": "Mostrado en privado"
};
