/** Spanish for the journal. */
export const JOURNAL_ES = {
  "That could not be done.": "No se pudo hacer.",
  "You are not connected to the room right now.": "Ahora mismo no estás conectado a la sala.",
  "Journal": "Diario",
  "Recap": "Resumen",
  "Party journal": "Diario del grupo",
  "My notes": "Mis notas",
  "Note": "Nota",
  "Entry": "Entrada",
  "Only you can see these. They stay in this browser and in your exports.": "Solo tú ves esto. Se queda en este navegador y en tus exportaciones.",
  "No notes yet.": "Todavía no hay notas.",
  "Nothing here yet. Write down what the crew knows: clues, names, the terms of a Contract.": "Todavía no hay nada. Anota lo que sabe el equipo: pistas, nombres, las condiciones de un Contrato.",
  "Write here.": "Escribe aquí.",
  "Edit entry": "Editar entrada",
  "Unpin": "Desfijar",
  "Pin": "Fijar",
  "This cannot be undone.": "No se puede deshacer.",
  "That is the most notes this app keeps.": "Es el máximo de notas que guarda esta aplicación.",
  "New note": "Nota nueva",
  "New journal entry": "Entrada de diario nueva",
  "Session recap": "Resumen de sesión",
  "New recap": "Resumen nuevo",
  "What happened": "Qué pasó",
  "Scenes": "Escenas",
  "Shown to the table": "Mostrado a la mesa",
  "What the crew now knows": "Lo que el equipo sabe ahora",
  "Open threads": "Hilos abiertos",
  "Next time": "La próxima vez"
};
