/** The bundled maps and tokens (generated by make_maps.py). Positions are in the shipped image's pixels. */
export const MAPS = [
 {
  "id": "backstreet",
  "title": "Backstreet: Threadmill Row",
  "file": "maps/backstreet.jpg",
  "w": 2100,
  "h": 1400,
  "cell": 70,
  "grid": true
 },
 {
  "id": "storefront",
  "title": "Fixer Office (small storefront)",
  "file": "maps/storefront.jpg",
  "w": 2100,
  "h": 1400,
  "cell": 70,
  "grid": true
 },
 {
  "id": "branch",
  "title": "Association Branch",
  "file": "maps/branch.jpg",
  "w": 2100,
  "h": 1400,
  "cell": 70,
  "grid": true
 },
 {
  "id": "atrium",
  "title": "Wing Nest Atrium",
  "file": "maps/atrium.jpg",
  "w": 2100,
  "h": 1400,
  "cell": 70,
  "grid": true
 },
 {
  "id": "warehouse",
  "title": "Syndicate Warehouse",
  "file": "maps/warehouse.jpg",
  "w": 2100,
  "h": 1400,
  "cell": 70,
  "grid": true
 },
 {
  "id": "breach",
  "title": "Abnormality Containment Breach",
  "file": "maps/breach.jpg",
  "w": 2100,
  "h": 1400,
  "cell": 70,
  "grid": true
 },
 {
  "id": "rooftop",
  "title": "Rooftop Chase",
  "file": "maps/rooftop.jpg",
  "w": 2100,
  "h": 1400,
  "cell": 70,
  "grid": true
 },
 {
  "id": "city",
  "title": "City Overview",
  "file": "maps/city.jpg",
  "w": 2400,
  "h": 1600,
  "cell": 0,
  "grid": false
 }
];
export const TOKENS = ["Generic_Cargo", "Generic_Enemy", "NPC_Clerk_Sorel", "NPC_Ines_Calloway", "NPC_Marl_Vessey", "NPC_Ottoline_Vance", "NPC_Rival_Crew_Lookout", "NPC_Sable_Rennick", "NPC_The_Stranger", "PC_Dax_Verrin", "PC_Lena_Hart", "PC_Tomas_Quill", "PC_Wren_Okoro"];
