/** Spanish for the shared-room interface (and the errors the room reports). */
export const ROOM_ES = {
  "The GM started a new scene.": "El DJ ha empezado una escena nueva.",
  "GM": "DJ",
  "Room": "Sala",
  "Connecting...": "Conectando...",
  "Say something to the table": "Di algo a la mesa",
  "Send": "Enviar",
  "Everyone": "Todos",
  "At the table": "En la mesa",
  "Nobody else is here yet.": "Todavía no hay nadie más.",
  "{owner}'s sheet (read only)": "Ficha de {owner} (solo lectura)",
  "Shown to the table": "Visible para la mesa",
  "Show to the table": "Mostrar a la mesa",
  "This Threat is now shown to the table.": "Esta Amenaza ahora es visible para la mesa.",
  "This Threat is hidden again.": "Esta Amenaza vuelve a estar oculta.",
  "Shared rooms need an internet connection (they load PeerJS).": "Las salas compartidas necesitan conexión a internet (cargan PeerJS).",
  "Room open": "Sala abierta",
  "Share the code {code} or the link. Players keep their own sheets; everyone sees the rolls.": "Comparte el código {code} o el enlace. Cada jugador lleva su ficha; todos ven las tiradas.",
  "Room {code}": "Sala {code}",
  "Leave room": "Salir de la sala",
  "You are the GM and host. Keep this page open: the room closes if you leave.": "Eres el DJ y el anfitrión. Mantén esta página abierta: la sala se cierra si te vas.",
  "You are in this room as {name}.": "Estás en esta sala como {name}.",
  "Code": "Código",
  "Link": "Enlace",
  "Here now": "Ahora aquí",
  "Nobody else yet.": "Nadie más todavía.",
  "You left the room.": "Has salido de la sala.",
  "Shared rooms connect your browsers directly (through the free PeerJS broker). The GM hosts and must keep the page open. Players keep their own sheets; everyone sees the rolls.": "Las salas compartidas conectan vuestros navegadores directamente (mediante el servicio gratuito PeerJS). El DJ es el anfitrión y debe mantener la página abierta. Cada jugador lleva su ficha; todos ven las tiradas.",
  "I am the GM: open a room": "Soy el DJ: abrir una sala",
  "I am a player: join a room": "Soy jugador: unirme a una sala",
  "Your name": "Tu nombre",
  "Shared room": "Sala compartida",
  "Go": "Adelante",
  "Enter your name first.": "Escribe primero tu nombre.",
  "Enter a room code.": "Escribe un código de sala.",
  "That code is already in use. Another host may still be connected.": "Ese código ya está en uso. Puede que otro anfitrión siga conectado.",
  "Could not reach the PeerJS broker. Check your connection.": "No se pudo contactar con PeerJS. Comprueba tu conexión.",
  "No room with that code. Check it, and that the GM has the page open.": "No hay ninguna sala con ese código. Revísalo, y que el DJ tenga la página abierta.",
  "Could not reach the room. Check the code and your connection.": "No se pudo llegar a la sala. Revisa el código y tu conexión.",
  "The GM left the room.": "El DJ ha salido de la sala."
};
