/** Spanish for the shared-room interface (and the errors the room reports). */
export const ROOM_ES = {
  "The GM started a new scene.": "El DJ ha empezado una escena nueva.",
  "GM": "DJ",
  "Room": "Sala",
  "Connecting...": "Conectando...",
  "Say something to the table": "Di algo a la mesa",
  "Send": "Enviar",
  "Everyone": "Todos",
  "At the table": "En la mesa",
  "Nobody else is here yet.": "Todavía no hay nadie más.",
  "{owner}'s sheet (read only)": "Ficha de {owner} (solo lectura)",
  "Shown to the table": "Visible para la mesa",
  "Show to the table": "Mostrar a la mesa",
  "This Threat is now shown to the table.": "Esta Amenaza ahora es visible para la mesa.",
  "This Threat is hidden again.": "Esta Amenaza vuelve a estar oculta.",
  "Shared rooms need an internet connection (they load PeerJS).": "Las salas compartidas necesitan conexión a internet (cargan PeerJS).",
  "Room open": "Sala abierta",
  "Share the code {code} or the link. Players keep their own sheets; everyone sees the rolls.": "Comparte el código {code} o el enlace. Cada jugador lleva su ficha; todos ven las tiradas.",
  "Room {code}": "Sala {code}",
  "Leave room": "Salir de la sala",
  "You are the GM and host. Keep this page open: the room closes if you leave.": "Eres el DJ y el anfitrión. Mantén esta página abierta: la sala se cierra si te vas.",
  "You are in this room as {name}.": "Estás en esta sala como {name}.",
  "Code": "Código",
  "Link": "Enlace",
  "Here now": "Ahora aquí",
  "Nobody else yet.": "Nadie más todavía.",
  "You left the room.": "Has salido de la sala.",
  "Shared rooms connect your browsers directly (through the free PeerJS broker). The GM hosts and must keep the page open. Players keep their own sheets; everyone sees the rolls.": "Las salas compartidas conectan vuestros navegadores directamente (mediante el servicio gratuito PeerJS). El DJ es el anfitrión y debe mantener la página abierta. Cada jugador lleva su ficha; todos ven las tiradas.",
  "I am the GM: open a room": "Soy el DJ: abrir una sala",
  "I am a player: join a room": "Soy jugador: unirme a una sala",
  "Your name": "Tu nombre",
  "Shared room": "Sala compartida",
  "Go": "Adelante",
  "Enter your name first.": "Escribe primero tu nombre.",
  "Enter a room code.": "Escribe un código de sala.",
  "That code is already in use. Another host may still be connected.": "Ese código ya está en uso. Puede que otro anfitrión siga conectado.",
  "Could not reach the PeerJS broker. Check your connection.": "No se pudo contactar con PeerJS. Comprueba tu conexión.",
  "No room with that code. Check it, and that the GM has the page open.": "No hay ninguna sala con ese código. Revísalo, y que el DJ tenga la página abierta.",
  "Could not reach the room. Check the code and your connection.": "No se pudo llegar a la sala. Revisa el código y tu conexión.",
  "Reconnected.": "Reconectado.",
  "Reconnecting...": "Reconectando...",
  "Reopening room {code}...": "Reabriendo la sala {code}...",
  "Lost the room. Reconnecting to {code}...": "Se perdió la sala. Reconectando a {code}...",
  "Stop trying": "Dejar de intentarlo",
  "The room service answered in {ms} ms.": "El servicio de salas respondió en {ms} ms.",
  "Could not reach the room service (PeerJS). Check your internet connection, or that this network does not block it.": "No se pudo contactar con el servicio de salas (PeerJS). Revisa tu conexión a internet o que esta red no lo bloquee.",
  "A relay is working, so rooms should connect even on strict networks.": "Hay un relé funcionando, así que las salas deberían conectar incluso en redes estrictas.",
  "Your network gave a public address, so direct rooms should work for most people. Some strict networks (schools, offices, mobile data) can still block them; a relay fixes that.": "Tu red dio una dirección pública, así que las salas directas deberían funcionar para casi todos. Algunas redes estrictas (colegios, oficinas, datos móviles) aún pueden bloquearlas; un relé lo soluciona.",
  "Your network gave only a local address: direct rooms will probably fail. Try another network, or add a relay under Connection.": "Tu red solo dio una dirección local: las salas directas probablemente fallarán. Prueba otra red o añade un relé en Conexión.",
  "Could not test the network (this browser may not allow it).": "No se pudo probar la red (puede que este navegador no lo permita).",
  "Lock the room (nobody new can join; people who were already in can come back)": "Bloquear la sala (nadie nuevo puede entrar; quienes ya estaban pueden volver)",
  "Password": "Contraseña",
  "none": "ninguna",
  "You are the GM and host. If your page closes or reloads, it reopens this room by itself and players come back; if you leave on purpose the room is closed.": "Eres el DJ y el anfitrión. Si tu página se cierra o se recarga, reabre esta sala sola y los jugadores vuelven; si te vas a propósito, la sala se cierra.",
  "You are in this room as {name}. If the connection drops, this page keeps trying to get back in.": "Estás en esta sala como {name}. Si se corta la conexión, esta página sigue intentando volver a entrar.",
  "Password set.": "Contraseña establecida.",
  "Password removed.": "Contraseña quitada.",
  "{name} was removed from the room.": "{name} ha sido expulsado de la sala.",
  "This keeps trying by itself for ten minutes. Nothing you have written is lost.": "Esto sigue intentándolo solo durante diez minutos. No se pierde nada de lo que has escrito.",
  "optional": "opcional",
  "Connection": "Conexión",
  "Test my connection": "Probar mi conexión",
  "Relay (advanced, optional): one per line, like  turn:host:3478  username  password": "Relé (avanzado, opcional): uno por línea, como  turn:host:3478  usuario  contraseña",
  "Only needed if rooms will not connect on your network. Kept on this device only.": "Solo hace falta si las salas no conectan en tu red. Se guarda solo en este dispositivo.",
  "Testing...": "Probando...",
  "Some relay lines were ignored (line {n}).": "Algunas líneas del relé se ignoraron (línea {n}).",
  "Wrong or missing room password.": "Contraseña de sala incorrecta o ausente.",
  "The GM has locked the room to new players.": "El DJ ha bloqueado la sala a jugadores nuevos.",
  "The GM removed you from this room.": "El DJ te ha expulsado de esta sala.",
  "Could not reconnect. Check your connection, then join again.": "No se pudo reconectar. Revisa tu conexión y vuelve a unirte.",
  "The connection to the broker was lost.": "Se perdió la conexión con el servicio de salas.",
  "The room closed unexpectedly.": "La sala se cerró inesperadamente.",
  "The GM left the room.": "El DJ ha salido de la sala."
};
