/** Spanish for the backup and data-safety screens. */
export const SAFETY_ES = {
  "Backup": "Copia",
  "Could not save in this browser. Your latest changes may be lost. Export a copy now.": "No se pudo guardar en este navegador. Puede que pierdas los últimos cambios. Exporta una copia ahora.",
  "Export now": "Exportar ahora",
  "The browser needs your permission to keep writing the backup file.": "El navegador necesita tu permiso para seguir escribiendo el archivo de copia.",
  "Allow": "Permitir",
  "Your changes have not been backed up since {when}.": "Tus cambios no se han respaldado desde {when}.",
  "Backups": "Copias de seguridad",
  "Save this character as a file": "Guardar este personaje como archivo",
  "{name} exported. Send the file to anyone; they can Import it.": "{name} exportado. Envía el archivo a quien quieras; puede Importarlo.",
  "Automatic": "Automática",
  "Before an import": "Antes de una importación",
  "Restore": "Restaurar",
  "Your browser cannot write a backup file by itself (Chrome and Edge on a computer can). Use Export now and then.": "Tu navegador no puede escribir un archivo de copia por sí solo (Chrome y Edge en ordenador sí). Usa Exportar de vez en cuando.",
  "Writing every change to your backup file. {state}": "Escribiendo cada cambio en tu archivo de copia. {state}",
  "It is up to date.": "Está al día.",
  "The browser needs you to allow it again.": "El navegador necesita que lo permitas otra vez.",
  "No backup file chosen.": "No has elegido archivo de copia.",
  "Last export": "Última exportación",
  "Export everything": "Exportar todo",
  "Import a file": "Importar un archivo",
  "To move one character to another device or a friend, open it and press Export on its sheet.": "Para llevar un personaje a otro dispositivo o a un amigo, ábrelo y pulsa Exportar en su ficha.",
  "Backup file": "Archivo de copia",
  "Choose another file": "Elegir otro archivo",
  "Choose a backup file": "Elegir un archivo de copia",
  "Stop": "Parar",
  "Snapshots the app keeps": "Instantáneas que guarda la aplicación",
  "None yet. One is taken about every ten minutes of changes, and before any import.": "Todavía ninguna. Se toma una cada diez minutos de cambios, y antes de cada importación.",
  "Browser storage": "Almacenamiento del navegador",
  "Protected: the browser will not clear this data when it is short of space.": "Protegido: el navegador no borrará estos datos aunque le falte espacio.",
  "Not protected: if the browser is short of space it may clear this data.": "Sin proteger: si al navegador le falta espacio, puede borrar estos datos.",
  "Using {used} of about {total}.": "Usando {used} de unos {total}.",
  "Ask the browser to keep my data": "Pedir al navegador que conserve mis datos",
  "Your data is now protected.": "Tus datos ahora están protegidos.",
  "The browser did not agree. Exporting a file is the safe way.": "El navegador no aceptó. Exportar un archivo es la forma segura.",
  "Backup file ready.": "Archivo de copia listo.",
  "Go back to this snapshot? What you have now is kept as a snapshot first.": "¿Volver a esta instantánea? Lo que tienes ahora se guarda antes como instantánea.",
  "Restored.": "Restaurado.",
  "Imported {name}.": "{name} importado.",
  "Importing replaces everything in this browser. A snapshot of what you have now is kept first, so you can go back.": "Importar reemplaza todo en este navegador. Antes se guarda una instantánea de lo que tienes ahora, para que puedas volver.",
  "never": "nunca",
  "just now": "ahora mismo",
  "{n} minutes ago": "hace {n} minutos",
  "{n} hours ago": "hace {n} horas",
  "{n} days ago": "hace {n} días",
  "That file is too large.": "Ese archivo es demasiado grande.",
  "That file is not valid.": "Ese archivo no es válido.",
  "Not a Project Moon file.": "No es un archivo de Project Moon."
};
