/**
 * Spanish for the GM screen. Keys are the English strings in screen.mjs. The wording follows the Spanish manual (Apéndices B a H, Partes VI y VIII),
 * so the screen and the book use the same terms: Reserva, Éxito, Fallo, Punto de Quiebre, Último Recurso, Distorsión, Rastro, Sintonizado, Perjudicadas.
 */
export const SCREEN_ES = {
  "GM screen": "Pantalla del DJ",
  "Search the rules": "Buscar en las reglas",
  "Nothing matches.": "Nada coincide.",
  "Quick references from the manual (Appendices B to H).": "Referencias rápidas del manual (Apéndices B a H).",
  "Screen": "Pantalla",

  "The Core Roll": "La Tirada Básica",
  "E.G.O., Stress and Harm": "E.G.O., Estrés y Daño",
  "Clocks": "Relojes",
  "Threat Grade": "Grado y Grado de Amenaza",
  "GM quick templates": "Plantillas Rápidas para el DJ",
  "The Sins": "Los Pecados",
  "Resources and attuned gear": "Recursos y Equipo Sintonizado",

  "Pool = Attribute + Skill (Attribute alone if untrained). Roll that many d10s. A 7, 8, 9 or 10 is a Success.": "Reserva = Atributo + Habilidad (o solo Atributo si no está entrenado). Tira esa cantidad de d10. Un 7, 8, 9 o 10 es un Éxito.",
  "What it represents": "Qué representa",
  "Routine, but not risk-free": "Rutinario, pero no exento de riesgo",
  "Genuinely challenging, professional-grade": "Genuinamente desafiante, nivel profesional",
  "The City actively pushing back": "La Ciudad presionando activamente en contra",
  "Exceptional: needs prep, Help, or E.G.O.": "Excepcional: necesita preparación, Ayuda, o E.G.O.",
  "Result": "Resultado",
  "Successes vs. Difficulty": "Éxitos vs. Dificultad",
  "Difficulty + 2 or more": "Dificultad + 2 o más",
  "Difficulty or more": "Dificultad o más",
  "Difficulty - 1": "Dificultad − 1",
  "Difficulty - 2 or less": "Dificultad − 2 o menos",
  "0 Successes and at least one die shows 1 (checked first; E.G.O. dice count)": "0 Éxitos y al menos un dado muestra 1 (se comprueba primero; los dados de E.G.O. cuentan)",
  "**Opposed rolls:** compare Successes from the side trying to change things. Margin +3 or more: Critical Success. +1 or +2: Success. 0 or -1: Partial. -2 or worse: Failure. Ties favor the defender.": "**Tiradas enfrentadas:** compara los Éxitos desde el bando que intenta cambiar las cosas. Margen +3 o más: Éxito Crítico. +1 o +2: Éxito. 0 o −1: Parcial. −2 o peor: Fallo. Los empates favorecen al defensor.",
  "At Difficulty 1 there is no Failure band; the worst ordinary result is a Partial.": "Con Dificultad 1 no existe la banda de Fallo; el peor resultado ordinario es un Parcial.",
  "Die showing 1": "Dado que muestra 1",
  "Effect": "Efecto",
  "Any die, with zero Successes in the roll": "Cualquier dado, con cero Éxitos en la tirada",
  "Any die, while Unsteady": "Cualquier dado, estando Inestable",
  "The first 1 each scene triggers a Flashpoint": "El primer 1 de cada escena dispara un Punto de Quiebre",
  "Any die, while Empty": "Cualquier dado, estando Vacío",
  "Every roll showing a 1 triggers a Flashpoint (one per roll)": "Toda tirada con un 1 dispara un Punto de Quiebre (uno por tirada)",
  "An E.G.O. die showing 1 or 2": "Un dado de E.G.O. que muestre 1 o 2",
  "A Complication": "Una Complicación",

  "**Spending E.G.O.:** 1 E.G.O. = 1 extra die. Any die showing 1-2 = one Complication.": "**Gastar E.G.O.:** 1 E.G.O. = 1 dado extra. Cualquier dado que muestre 1–2 = una Complicación.",
  "**Recovering E.G.O.:** +1 per full night's rest, +1 more per genuine downtime scene. Maximum +2 between Contracts.": "**Recuperar E.G.O.:** +1 por noche completa de descanso, +1 más por escena genuina de tiempo libre. Máximo +2 entre Contratos.",
  "**Running low:** below half E.G.O. maximum (judged at the start of the roll, before spending), a character is Unsteady. At 0 E.G.O., a character is Empty. A maximum of 2 or less skips Unsteady.": "**Quedarse corto:** con el E.G.O. actual por debajo de la mitad del máximo (al empezar la tirada, antes de gastar), un personaje está Inestable. Con 0 E.G.O., está Vacío. Un máximo de 2 o menos se salta Inestable.",
  "**What raises Stress:** +1 for a Trauma trigger, a Boundary violation, a Critical Failure, a Bond lost outright, or an E.G.O. Manifestation. +2 for a Distortion. Stress only comes down through downtime tied to a Bond (-1, at most once between Contracts) or a Reckoning. At Stress 2+, a forced E.G.O. loss takes 1 extra point; at Stress 4+, 2 extra.": "**Qué sube el Estrés:** +1 por un disparador de Trauma, una violación de Límite, un Fallo Crítico, un Vínculo perdido del todo, o una Manifestación de E.G.O. +2 por una Distorsión. El Estrés solo baja mediante tiempo libre ligado a un Vínculo (−1, como máximo una vez entre Contratos) o un Ajuste de Cuentas. Con Estrés 2 o más, una pérdida forzada de E.G.O. cuesta 1 punto extra; con Estrés 4 o más, 2 extra.",
  "Stress": "Estrés",
  "E.G.O. max modifier": "Modificador al E.G.O. máximo",
  "None": "Ninguno",
  "-2, and Fraying (+1 Difficulty on Hail Mary)": "−2, y Quebradizo (+1 Dificultad en el Último Recurso)",
  "E.G.O. maximum never drops below 1.": "El E.G.O. máximo nunca baja de 1.",
  "Harm": "Daño",
  "Injured": "Herido",
  "Wounded": "Malherido",
  "No penalty": "Sin penalización",
  "-1 die": "−1 dado",
  "-2 dice, needs treatment": "−2 dados, necesita tratamiento",
  "Out of the scene": "Fuera de la escena",
  "**The Hail Mary:** triggers when E.G.O. would hit 0 at a Boundary-level moment, or when a player digs deep (spends all remaining E.G.O., at least 2, and +1 Difficulty; not on a line with an unhealed Scar). A Success needs an **Acceptance** (the character states what they accept about themselves) or it becomes a Partial Distortion. Resolve + relevant Skill, Difficulty 2-3. -1 die per Boundary already broken this campaign; may spend a Bond for +1 die.": "**El Último Recurso:** se dispara cuando el E.G.O. llegaría a 0 en un momento de nivel de Límite, o cuando un jugador cava hondo (gasta todo el E.G.O. restante, al menos 2, y +1 de Dificultad; no en una línea con una Cicatriz sin sanar). Un Éxito necesita una **Aceptación** (el personaje dice qué acepta de sí mismo) o se convierte en una Distorsión Parcial. Voluntad + Habilidad relevante, Dificultad 2–3. −1 dado por cada Límite ya cruzado esta campaña; puede gastarse un Vínculo por +1 dado.",
  "Hail Mary result": "Resultado del Último Recurso",
  "Outcome": "Consecuencia",
  "E.G.O. Manifestation, clean. Stress +1.": "Manifestación de E.G.O., limpia. Estrés +1.",
  "E.G.O. Manifestation, at a cost. Stress +1.": "Manifestación de E.G.O., a un coste. Estrés +1.",
  "Partial Distortion: transformed and monstrous, but the character keeps the wheel. Stress +2.": "Distorsión Parcial: genuinamente transformado y monstruoso, pero el personaje conserva el control. Estrés +2.",
  "Complete Distortion: the self is pushed out; lasts until the fiction brings them back. Stress +2.": "Distorsión Completa: el yo queda desplazado; dura hasta que la ficción lo trae de vuelta. Estrés +2.",
  "Complete Distortion, already severe: death or permanence are live options. Stress +2.": "Distorsión Completa, ya en su punto más grave: la muerte o la permanencia son opciones vivas desde el principio. Estrés +2.",

  "Size": "Tamaño",
  "Use for": "Úsalo para",
  "4 segments": "4 segmentos",
  "6 segments": "6 segmentos",
  "8 segments": "8 segmentos",
  "Scene-level, immediate pressure": "A nivel de escena, presión inmediata",
  "Faction Heat, spans several sessions": "Presión de facción, se extiende varias sesiones",
  "Campaign-length stakes": "Lo que está en juego a nivel de campaña",
  "Fill 1 segment per meaningful setback, never more than 2.": "Rellena 1 segmento por revés significativo, nunca más de 2.",

  "Dice it rolls": "Dados que tira",
  "Typical treatment": "Tratamiento típico",
  "Single mook / Threat track": "Esbirro único / rastro de Amenaza",
  "Capable individual / Threat-tracked group": "Individuo capaz / grupo llevado como Amenaza",
  "Named opponent, full Harm track": "Oponente con nombre, rastro de Daño completo",
  "Named opponent, needs a full crew": "Oponente con nombre, necesita un equipo completo",
  "A group adds 2 dice. A Threat track runs Holding, Breaking, Routed; a Critical Success against a Threat at Holding pushes it straight to Breaking.": "Un grupo suma 2 dados. El rastro de una Amenaza va de Resistiendo a Cediendo y a Derrotada; un Éxito Crítico contra una Amenaza en Resistiendo la empuja directamente a Cediendo.",
  "**Solo named opponents facing a full party:** a named opponent of Threat Grade 4 or lower gets one additional defensive response each Exchange: a second Defense roll against a different attacker, or a single counter-Harm reply against whoever just landed a hit. It is not an extra action, and it does not stack with itself.": "**Oponentes con nombre en solitario frente a un grupo completo:** un oponente con nombre de Grado de Amenaza 4 o inferior obtiene una respuesta defensiva adicional en cada Intercambio: una segunda tirada de Defensa contra un atacante distinto, o una única réplica de Daño contra quien acabe de impactarlo. No es una segunda acción ni un turno extra, y no se acumula consigo misma.",
  "**Retreat:** a character may concede before an Exchange resolves (no further Harm; the GM sets the terms) or try to retreat with an opposed roll; failing costs a further Exchange.": "**Retirada y Rendición:** un personaje puede rendirse antes de que se resuelva un Intercambio (no sufre más Daño; el DJ fija los términos) o intentar retirarse con una tirada enfrentada; fallar la retirada cuesta un Intercambio más.",

  "Template": "Plantilla",
  "Parts": "Partes",
  "NPC": "PNJ",
  "Want, Bond hook, One detail (and Alignment)": "Quiere — Gancho de Vínculo — Un Detalle (— Alineamiento)",
  "Contract": "Contrato",
  "Client, Objective, Payment, Complication Clause, Risk (1-4)": "Cliente — Objetivo — Pago — Cláusula de Complicación — Riesgo (1–4)",
  "District": "Distrito",
  "Name, Dominant institution, Texture, Tension, Clock": "Nombre — Institución Dominante — Textura — Tensión — Reloj",
  "Wing": "Ala",
  "Industry, Singularity connection, Employment flavor, Secret, Whose suffering?": "Industria — Conexión con la Singularidad — Sabor del Empleo — Secreto — ¿El sufrimiento de quién?",
  "Syndicate": "Sindicato",
  "Territory, Racket, Recruitment style, Escalation ladder (3 steps), Terms, Flavor": "Territorio — Negocio — Estilo de Reclutamiento — Escalera de Escalada (3 pasos) — Términos — Estilo",
  "Risk": "Riesgo",
  "Calibration": "Calibración",
  "A clear, safe path and a forgiving Complication Clause": "Un camino claro y seguro y una Cláusula de Complicación indulgente",
  "One genuine unknown": "Una incógnita genuina",
  "At least one Social Conflict or Combat scene of real consequence, engaging a PC's Bond, Desire or Fear": "Garantiza al menos una escena de Conflicto Social o Combate con consecuencias reales, que implique el Vínculo, Deseo o Miedo de al menos un PJ",
  "Touches the psychological layer: a Trauma trigger or Hail Mary should be plausible": "Toca la capa psicológica directamente: un disparador de Trauma o un Último Recurso deberían ser plausibles",

  "**Resonance:** 6 points at creation, max 3; the highest Sin is the Alignment. Rating 1 is a flicker; rating 2 or more does things. Signature Technique at 2+.": "**Resonancia:** 6 puntos al crear, máximo 3; el Pecado más alto es el Alineamiento. Puntuación 1 es un destello; con 2 o más hace cosas. Técnica Distintiva con 2+.",
  "Sin": "Pecado",
  "Strong against": "Fuerte contra",
  "Weak against": "Débil contra",
  "Favored": "Favorecidas",
  "Hindered": "Perjudicadas",
  "The wheel runs Sloth, Wrath, Pride, Envy, Gluttony, Lust, Gloom: each Sin is strong against the next two and weak against the two before.": "La rueda va así: Pereza, Ira, Orgullo, Envidia, Gula, Lujuria, Melancolía. Cada Pecado es fuerte contra los dos siguientes y débil contra los dos anteriores.",
  "**Swing:** Strong +1 die, Weak -1 die (2 at rating 4, 3 at rating 5). Needs rating 2+. Matchup plus Fit never beyond 3.": "**Vaivén:** Fuerte +1 dado, Débil −1 dado (±2 con puntuación 4, ±3 con 5). Necesita puntuación 2+. Enfrentamiento más Encaje nunca más allá de ±3.",
  "**Fit (only while Under a Sin):** Favored +1, Hindered -2 (+2 / -3 at rating 4+).": "**Encaje (solo Bajo un Pecado):** Favorecida +1, Perjudicada −2 (+2 / −3 con puntuación 4+).",
  "**Under a Sin:** Riding it (free, one per scene); its Urge took your Flashpoint; Distorted; Overtaken (4) and Unsteady or Empty; Saturated (5).": "**Bajo un Pecado:** Cabalgándolo (gratis, uno por escena); su Impulso se llevó tu Punto de Quiebre; Distorsionado; Desbordado (4) e Inestable o Vacío; Saturado (5).",
  "**Drift:** every fourth session, a Sin leading by 8 or more tags gains +1 (max 4); the least-tagged Sin loses 1. **Saturated (5):** always Under, must tag each scene or +1 Stress.": "**Deriva:** cada cuarta sesión, un Pecado que aventaja por 8 o más etiquetas gana +1 (máx. 4); el menos etiquetado pierde 1. **Saturado (5):** siempre Bajo, debe etiquetar cada escena o +1 de Estrés.",
  "**With the Self:** an E.G.O. Complication on a tagged roll is the Sin's; refunds are capped at 2 E.G.O. per scene; Permanent E.G.O. counts as rating 4; Distorted characters are Exposed (+1 die against them from any Sin that beats theirs).": "**Con el Yo:** la Complicación de E.G.O. en una tirada etiquetada es la del Pecado; reembolsos con tope de 2 E.G.O. por escena; el E.G.O. Permanente cuenta como puntuación 4; los Distorsionados están Expuestos (+1 dado contra ellos de cualquier Pecado que venza al suyo).",

  "**Resources:** 0 to 5, start 2. A Contract pays Resources equal to its Risk (minus 1 for the Office's cut at Risk 3 or 4). Each downtime phase costs 1. Cost: 1 armor, Light weapon, kit; 2 Heavy weapon, attuned gear, Backstreets augmentation; 3 Fine attuned gear, Nest augmentation; 4 Workshop extraction. Short of money: a Debt Bond (up to 3).": "**Recursos:** 0 a 5, se empieza con 2. Un Contrato paga Recursos iguales a su Riesgo (menos 1 por el recorte de la Oficina en Riesgo 3 o 4). Cada fase de tiempo libre cuesta 1. Coste: 1 armadura, arma Ligera, botiquín; 2 arma Pesada, equipo sintonizado, aumento de los Callejones; 3 equipo sintonizado Fino, aumento del Nido; 4 extracción en Taller. Si falta dinero: un Vínculo de Deuda (hasta 3).",
  "**Attuned gear:** Weapon +1 die on attacks tagged with its Sin; Suit +1 die on defense tagged with its Sin; Tool +1 die on a tagged roll using a Favored Skill of the Sin; Charm ignores the Sin's Complication once per scene. Fine (Cost 3): +2 if attuned at rating 3+.": "**Equipo sintonizado:** Arma +1 dado en ataques etiquetados con su Pecado; Traje +1 dado en defensa etiquetada con su Pecado; Herramienta +1 dado en una tirada etiquetada que use una Habilidad Favorecida del Pecado; Amuleto ignora la Complicación del Pecado una vez por escena. Fino (Coste 3): +2 si estás sintonizado con puntuación 3+.",
  "**Attuned** = your rating in its Sin is 2+. **Borrowed** = rating 0 or 1: tag as if rating 2 (swing 1), no Fit, no Riding, no technique.": "**Sintonizado** = tu puntuación en su Pecado es 2+. **Prestado** = puntuación 0 o 1: etiqueta como si fuera 2 (vaivén ±1), sin Encaje, sin Cabalgar, sin técnica.",
  "**Price:** Pull (the Sin's Complication on the first 1 each scene; every 1 if borrowing, Under, or Overtaken); Tally (a mark for the Sin; two if borrowing); Wear (1 per Pull; Spent at 3, repair costs 1 Resources and a downtime action).": "**Precio:** Tirón (la Complicación del Pecado con el primer 1 de cada escena; cada 1 si lo tomas prestado, estás Bajo o Desbordado); Cuenta (una marca para el Pecado; dos si es prestado); Desgaste (1 por Tirón; Agotado con 3, repararlo cuesta 1 Recurso y una acción de tiempo libre).",
  "**Limits:** one Boon per roll; matchup + Fit + Boon never beyond +4; two pieces at once (three or more: all Pull on every 1).": "**Límites:** un Bono por tirada; enfrentamiento + Encaje + Bono nunca más de +4; dos piezas a la vez (tres o más: todas Tiran con cada 1)."
};
