/** Spanish for the Threat library. */
export const THREAT_ES = {
  "Threats": "Amenazas",
  "Keep this Threat as a template in the Threats tab": "Guarda esta Amenaza como plantilla en la pestaña Amenazas",
  "Save to library": "Guardar en la biblioteca",
  "Attack": "Ataque",
  "Defense": "Defensa",
  "Track": "Marcador",
  "Use": "Uso",
  "Remove from my library": "Quitar de mi biblioteca",
  "Add to the encounter": "Añadir al encuentro",
  "No Threat matches.": "Ninguna Amenaza coincide.",
  "Add Threats with + to build an encounter. Dice come from the Grade (Appendix E).": "Añade Amenazas con + para montar un encuentro. Los dados salen del Grado (Apéndice E).",
  "one group": "un grupo",
  "A named opponent of Grade 4 or lower gets one extra defensive response each Exchange (Part VI).": "Un oponente con nombre de Grado 4 o menos tiene una respuesta defensiva extra en cada Intercambio (Parte VI).",
  "{n} Threat sheets": "{n} fichas de Amenaza",
  "{n} dice rolled against the crew per round, if every one acts": "{n} dados contra el equipo por ronda, si todas actúan",
  "Add to the Exchange order": "Añadir al orden del Intercambio",
  "Put tokens on the map": "Poner fichas en el mapa",
  "Create these Threats": "Crear estas Amenazas",
  "Clear": "Vaciar",
  "Backstreets": "Callejones",
  "Nests": "Nidos",
  "Special humans": "Humanos especiales",
  "Colors": "Colores",
  "Mine": "Mías",
  "Encounter": "Encuentro",
  "Search by name": "Buscar por nombre",
  "Any Grade": "Cualquier Grado",
  "Grade 9-8 (3 dice)": "Grado 9-8 (3 dados)",
  "Grade 7-5 (4 dice)": "Grado 7-5 (4 dados)",
  "Grade 4-2 (6 dice)": "Grado 4-2 (6 dados)",
  "Grade 1 (8 dice)": "Grado 1 (8 dados)",
  "Any Sin": "Cualquier Pecado",
  "Everything": "Todo",
  "Text comes from the Bestiary in English. Open a Threat sheet and press Save to library to keep your own.": "Los textos vienen del Bestiario, en inglés. Abre una ficha de Amenaza y pulsa Guardar en la biblioteca para conservar las tuyas.",
  "Choose a Sin": "Elige un Pecado",
  "Create": "Crear",
  "{n} Threat sheets created.": "{n} fichas de Amenaza creadas.",
  "That is the most templates this app keeps.": "Es el máximo de plantillas que guarda la app.",
  "{name} saved to your library.": "{name} guardada en tu biblioteca."
};
