/** Spanish for the Threat library. */
export const THREAT_ES = {
  "Threats": "Amenazas",
  "Keep this Threat as a template in the Threats tab": "Guarda esta Amenaza como plantilla en la pestaña Amenazas",
  "Save to library": "Guardar en la biblioteca",
  "Attack": "Ataque",
  "Defense": "Defensa",
  "Track": "Marcador",
  "Use": "Uso",
  "Remove from my library": "Quitar de mi biblioteca",
  "Add to the encounter": "Añadir al encuentro",
  "No Threat matches.": "Ninguna Amenaza coincide.",
  "Add Threats with + to build an encounter. Dice come from the Grade (Appendix E).": "Añade Amenazas con + para montar un encuentro. Los dados salen del Grado (Apéndice E).",
  "one group": "un grupo",
  "A named opponent of Grade 4 or lower gets one extra defensive response each Exchange (Part VI).": "Un oponente con nombre de Grado 4 o menos tiene una respuesta defensiva extra en cada Intercambio (Parte VI).",
  "{n} Threat sheets": "{n} fichas de Amenaza",
  "{n} dice rolled against the crew per round, if every one acts": "{n} dados contra el equipo por ronda, si todas actúan",
  "Add to the Exchange order": "Añadir al orden del Intercambio",
  "Put tokens on the map": "Poner fichas en el mapa",
  "Create these Threats": "Crear estas Amenazas",
  "Clear": "Vaciar",
  "Backstreets": "Callejones",
  "Nests": "Nidos",
  "Special humans": "Humanos especiales",
  "Colors": "Colores",
  "Mine": "Mías",
  "Encounter": "Encuentro",
  "Search by name": "Buscar por nombre",
  "Any Grade": "Cualquier Grado",
  "Grade 9-8 (3 dice)": "Grado 9-8 (3 dados)",
  "Grade 7-5 (4 dice)": "Grado 7-5 (4 dados)",
  "Grade 4-2 (6 dice)": "Grado 4-2 (6 dados)",
  "Grade 1 (8 dice)": "Grado 1 (8 dados)",
  "Any Sin": "Cualquier Pecado",
  "Everything": "Todo",
  "Text comes from the Bestiary in English. Open a Threat sheet and press Save to library to keep your own.": "Los textos vienen del Bestiario, en inglés. Abre una ficha de Amenaza y pulsa Guardar en la biblioteca para conservar las tuyas.",
  "Choose a Sin": "Elige un Pecado",
  "Create": "Crear",
  "{n} Threat sheets created.": "{n} fichas de Amenaza creadas.",
  "That is the most templates this app keeps.": "Es el máximo de plantillas que guarda la app.",
  "{name} saved to your library.": "{name} guardada en tu biblioteca.",
  "Tables": "Tablas",
  "Roll this part again": "Repetir esta parte",
  "Roll": "Tirar",
  "Roll again": "Tirar de nuevo",
  "Keep as a note": "Guardar como nota",
  "Saved to your notes.": "Guardado en tus notas.",
  "Clocks": "Relojes",
  "The players can see this Clock": "Los jugadores ven este Reloj",
  "Shown": "Visible",
  "No Clocks yet. Add the ones the table is racing: Open War, Heat, a chase.": "Aún no hay Relojes. Añade los que corren contra la mesa: Guerra Abierta, Calor, una persecución.",
  "The GM has not shown any Clocks.": "El DJ no ha mostrado ningún Reloj.",
  "Where": "Dónde",
  "When it fills": "Cuando se llena",
  "Players can see this Clock": "Los jugadores pueden ver este Reloj",
  "That is the most Clocks this app keeps.": "Es el máximo de Relojes que guarda la app.",
  "Edit Clock": "Editar Reloj",
  "Only the GM can import a kit.": "Solo el DJ puede importar un kit.",
  "Import kit": "Importar kit",
  "Add to what I have (nothing is replaced; names that already exist are kept)": "Añadir a lo que tengo (no se reemplaza nada; los nombres que ya existen se respetan)",
  "Only scenes and notes": "Solo escenas y notas",
  "Replace my Threats, scenes, handouts, notes, journal and Clocks (characters are kept)": "Reemplazar mis Amenazas, escenas, documentos, notas, diario y Relojes (los personajes se conservan)",
  "A snapshot of what you have now is kept first, so you can go back.": "Antes se guarda una copia de lo que tienes ahora, para poder volver atrás.",
  "Replace": "Reemplazar",
  "This replaces your Threats, scenes, handouts, notes, journal and Clocks with the kit's. Characters stay.": "Esto reemplaza tus Amenazas, escenas, documentos, notas, diario y Relojes por los del kit. Los personajes se quedan.",
  "Kit imported: {a} Threats, {s} scenes, {h} handouts, {n} notes, {c} Clocks.": "Kit importado: {a} Amenazas, {s} escenas, {h} documentos, {n} notas, {c} Relojes.",
  "{n} left as they were.": "{n} se dejaron como estaban.",
  "Session kits": "Kits de sesión",
  "Kits": "Kits",
  "Open": "Abrir",
  "A kit sets up a whole session at once: scenes, Threats, handouts, notes and Clocks.": "Un kit prepara una sesión entera de golpe: escenas, Amenazas, documentos, notas y Relojes.",
  "A kit file from my computer...": "Un archivo de kit de mi ordenador...",
  "That kit could not be opened.": "No se pudo abrir ese kit.",
  "That file is not a Project Moon kit.": "Ese archivo no es un kit de Project Moon.",
  "Session 01: The Row Shipment (Risk 3)": "Sesión 01: El Cargamento de la Fila (Riesgo 3)",
  "{n} scenes with maps": "{n} escenas con mapas",
  "{n} tokens": "{n} fichas",
  "{n} Threat sheets": "{n} fichas de Amenaza",
  "{n} handouts": "{n} documentos",
  "{n} private notes": "{n} notas privadas",
  "{n} journal entries": "{n} entradas del diario",
  "{n} Clocks": "{n} Relojes",
  "This sheet: {name}": "Esta ficha: {name}",
  "A blank character sheet": "Una ficha de personaje en blanco",
  "All handouts": "Todos los documentos",
  "The handouts I have been shown": "Los documentos que me han mostrado",
  "The party journal": "El diario del grupo",
  "My private notes": "Mis notas privadas",
  "The rules screen": "La pantalla de reglas",
  "The Clocks": "Los Relojes",
  "Print": "Imprimir",
  "This opens your browser's print window. Choose \"Save as PDF\" as the printer to make a file.": "Esto abre la ventana de impresión del navegador. Elige \"Guardar como PDF\" como impresora para obtener un archivo.",
  "Handouts: print both languages when there are two": "Documentos: imprimir los dos idiomas cuando haya dos",
  "Nothing to print there yet.": "Todavía no hay nada que imprimir ahí."
};
