/** Spanish for the Threat library. */
export const THREAT_ES = {
  "Threats": "Amenazas",
  "Keep this Threat as a template in the Threats tab": "Guarda esta Amenaza como plantilla en la pestaña Amenazas",
  "Save to library": "Guardar en la biblioteca",
  "Attack": "Ataque",
  "Defense": "Defensa",
  "Track": "Rastro",
  "Use in play": "Uso en juego",
  "Remove from my library": "Quitar de mi biblioteca",
  "Add to the encounter": "Añadir al encuentro",
  "No Threat matches.": "Ninguna Amenaza coincide.",
  "Add Threats with + to build an encounter. Dice come from the Grade (Appendix E).": "Añade Amenazas con + para montar un encuentro. Los dados salen del Grado (Apéndice E).",
  "one group": "un grupo",
  "A named opponent of Grade 4 or lower gets one extra defensive response each Exchange (Part VI).": "Un oponente con nombre de Grado de Amenaza 4 o inferior tiene una respuesta defensiva adicional en cada Intercambio (Parte VI).",
  "{n} Threat sheets": "{n} fichas de Amenaza",
  "{n} dice rolled against the crew per Exchange, if every one acts": "{n} dados contra el equipo por Intercambio, si todas actúan",
  "Add to the Exchange order": "Añadir al orden del Intercambio",
  "Put tokens on the map": "Poner fichas en el mapa",
  "Create these Threats": "Crear estas Amenazas",
  "Clear": "Vaciar",
  "Backstreets": "Callejones",
  "Nests": "Nidos",
  "Special humans": "Humanos especiales",
  "Colors": "Colores",
  "Mine": "Mías",
  "Encounter": "Encuentro",
  "Search by name": "Buscar por nombre",
  "Any Grade": "Cualquier Grado",
  "Grade 9-8 (3 dice)": "Grado 9-8 (3 dados)",
  "Grade 7-5 (4 dice)": "Grado 7-5 (4 dados)",
  "Grade 4-2 (6 dice)": "Grado 4-2 (6 dados)",
  "Grade 1 (8 dice)": "Grado 1 (8 dados)",
  "Any Sin": "Cualquier Pecado",
  "Everything": "Todo",
  "Text comes from the Bestiary in English. Open a Threat sheet and press Save to library to keep your own.": "Los textos vienen del Bestiario, en inglés. Abre una ficha de Amenaza y pulsa Guardar en la biblioteca para conservar las tuyas.",
  "Choose a Sin": "Elige un Pecado",
  "Create": "Crear",
  "{n} Threat sheets created.": "{n} fichas de Amenaza creadas.",
  "That is the most templates this app keeps.": "Es el máximo de plantillas que guarda la app.",
  "{name} saved to your library.": "{name} guardada en tu biblioteca.",
  "Tables": "Tablas",
  "Roll this part again": "Repetir esta parte",
  "Roll": "Tirar",
  "Roll again": "Tirar de nuevo",
  "Keep as a note": "Guardar como nota",
  "Saved to your notes.": "Guardado en tus notas.",
  "Clocks": "Relojes",
  "The players can see this Clock": "Los jugadores ven este Reloj",
  "Shown": "Visible",
  "No Clocks yet. Add the ones the table is racing: Open War, Heat, a chase.": "Aún no hay Relojes. Añade los que corren contra la mesa: Guerra Abierta, Presión, una persecución.",
  "The GM has not shown any Clocks.": "El DJ no ha mostrado ningún Reloj.",
  "Where": "Dónde",
  "When it fills": "Cuando se llena",
  "Players can see this Clock": "Los jugadores pueden ver este Reloj",
  "That is the most Clocks this app keeps.": "Es el máximo de Relojes que guarda la app.",
  "Edit Clock": "Editar Reloj",
  "Only the GM can import a kit.": "Solo el DJ puede importar un kit.",
  "Import kit": "Importar kit",
  "Add to what I have (nothing is replaced; names that already exist are kept)": "Añadir a lo que tengo (no se reemplaza nada; los nombres que ya existen se respetan)",
  "Only scenes and notes": "Solo escenas y notas",
  "Replace my Threats, scenes, handouts, notes, journal and Clocks (characters are kept)": "Reemplazar mis Amenazas, escenas, documentos, notas, diario y Relojes (los personajes se conservan)",
  "A snapshot of what you have now is kept first, so you can go back.": "Antes se guarda una copia de lo que tienes ahora, para poder volver atrás.",
  "Replace": "Reemplazar",
  "This replaces your Threats, scenes, handouts, notes, journal and Clocks with the kit's. Characters stay.": "Esto reemplaza tus Amenazas, escenas, documentos, notas, diario y Relojes por los del kit. Los personajes se quedan.",
  "Kit imported: {a} Threats, {s} scenes, {h} handouts, {n} notes, {c} Clocks.": "Kit importado: {a} Amenazas, {s} escenas, {h} documentos, {n} notas, {c} Relojes.",
  "{n} left as they were.": "{n} se dejaron como estaban.",
  "Session kits": "Kits de sesión",
  "Kits": "Kits",
  "Open": "Abrir",
  "A kit sets up a whole session at once: scenes, Threats, handouts, notes and Clocks.": "Un kit prepara una sesión entera de golpe: escenas, Amenazas, documentos, notas y Relojes.",
  "A kit file from my computer...": "Un archivo de kit de mi ordenador...",
  "That kit could not be opened.": "No se pudo abrir ese kit.",
  "That file is not a Project Moon kit.": "Ese archivo no es un kit de Project Moon.",
  "Session 01: The Row Shipment (Risk 3)": "Sesión 01: El Cargamento de la Fila (Riesgo 3)",
  "{n} scenes with maps": "{n} escenas con mapas",
  "{n} tokens": "{n} fichas",
  "{n} Threat sheets": "{n} fichas de Amenaza",
  "{n} handouts": "{n} documentos",
  "{n} private notes": "{n} notas privadas",
  "{n} journal entries": "{n} entradas del diario",
  "{n} Clocks": "{n} Relojes",
  "This sheet: {name}": "Esta ficha: {name}",
  "A blank character sheet": "Una ficha de personaje en blanco",
  "All handouts": "Todos los documentos",
  "The handouts I have been shown": "Los documentos que me han mostrado",
  "The party journal": "El diario del grupo",
  "My private notes": "Mis notas privadas",
  "The rules screen": "La pantalla de reglas",
  "The Clocks": "Los Relojes",
  "Print": "Imprimir",
  "This opens your browser's print window. Choose \"Save as PDF\" as the printer to make a file.": "Esto abre la ventana de impresión del navegador. Elige \"Guardar como PDF\" como impresora para obtener un archivo.",
  "Handouts: print both languages when there are two": "Documentos: imprimir los dos idiomas cuando haya dos",
  "Nothing to print there yet.": "Todavía no hay nada que imprimir ahí.",
  "Undo": "Deshacer",
  "Undo: {label}": "Deshacer: {label}",
  "Nothing to undo.": "No hay nada que deshacer.",
  "Undone: {label}": "Deshecho: {label}",
  "{name} took back the last change.": "{name} deshizo el último cambio.",
  "Someone": "Alguien",
  "Only you can see this": "Solo tú puedes ver esto",
  "Only you see the result, until you show it to the table.": "Solo tú ves el resultado, hasta que lo muestres a la mesa.",
  "Roll in secret": "Tirar en secreto",
  "Secret roll": "Tirada secreta",
  "What for": "Para qué",
  "the guard notices": "el guardia se da cuenta",
  "Dice": "Dados",
  "Threat roll": "Tirada de Amenaza",
  "Signature Technique": "Técnica Distintiva",
  "Upkeep": "Mantenimiento",
  "New scene": "Escena nueva",
  "Rest": "Descanso",
  "Riding a Sin": "Cabalgar un Pecado",
  "Gear wear": "Desgaste del equipo",
  "Downtime": "Tiempo libre",
  "Downtime for all": "Tiempo libre para todos",
  "New scene for all": "Escena nueva para todos",
  "Clock change": "Cambio de Reloj",
  "Exchange change": "Cambio en el Intercambio",
  "Condition change": "Cambio de condición",
  "Token removed": "Ficha quitada",
  "Sheet deleted": "Ficha borrada",
  "Scene deleted": "Escena borrada",
  "Item deleted": "Objeto borrado",
  "{name} earns Marks: {n}.": "{name} gana Marcas: {n}.",
  "Award Marks": "Dar Marcas",
  "Needs a Grade unlock": "Necesita un desbloqueo de Grado",
  "Not enough Marks": "No hay Marcas suficientes",
  "At the maximum": "En el máximo",
  "Raise": "Subir",
  "Skill 4": "Habilidad 4",
  "Attribute 5": "Atributo 5",
  "Skill 5": "Habilidad 5",
  "Grade {n}": "Grado {n}",
  "not yet": "aún no",
  "nothing is at {n} yet": "no hay nada en {n} todavía",
  "Marks spent: {n}": "Marcas gastadas: {n}",
  "Unspent Marks": "Marcas sin gastar",
  "Marks earned in total": "Marcas ganadas en total",
  "Spend Marks in downtime, in a scene that shows the training. A Skill costs its new rating; an Attribute costs three times its new rating. Skills stop at 3 and Attributes at 4 until a Grade unlock.": "Gasta las Marcas en el tiempo libre, en una escena que muestre el entrenamiento. Una Habilidad cuesta su nueva puntuación; un Atributo cuesta tres veces su nueva puntuación. Las Habilidades llegan hasta 3 y los Atributos hasta 4, hasta que un desbloqueo de Grado lo permita.",
  "Grade unlocks": "Desbloqueos de Grado",
  "Growth so far": "Crecimiento hasta ahora",
  "That cannot be raised now.": "Eso no se puede subir ahora.",
  "There are no characters to give Marks to.": "No hay personajes a quienes dar Marcas.",
  "Award": "Dar",
  "At the end of a Contract every player earns 1 Mark, plus 1 if it was Risk 3 or 4, plus 1 (once per session) for a played Reckoning or a scene that grew a Bond.": "Al final de un Contrato cada jugador gana 1 Marca, más 1 si fue Riesgo 3 o 4, más 1 (una vez por sesión) por un Ajuste de Cuentas jugado o una escena que hizo crecer un Vínculo.",
  "A Reckoning was played, or a scene grew a Bond": "Se jugó un Ajuste de Cuentas, o una escena hizo crecer un Vínculo",
  "Marks awarded": "Marcas otorgadas",
  "Marks each: {n} ({names})": "Marcas para cada uno: {n} ({names})",
  "Some players could not be reached.": "No se pudo avisar a algunos jugadores.",
  "Resolve rises, so the E.G.O. maximum rises by 1.": "La Voluntad sube, así que el máximo de E.G.O. sube 1.",
  "Growth": "Crecimiento",
  "rises to {n}": "sube a {n}",
  "Grade unlock": "Desbloqueo de Grado",
  "Drag on the map to draw": "Arrastra sobre el mapa para dibujar",
  "Draw": "Dibujar",
  "Click the map to leave a note": "Haz clic en el mapa para dejar una nota",
  "Click a drawing or a note to remove it": "Haz clic en un dibujo o una nota para quitarlo",
  "Erase": "Borrar",
  "Drawings are seen by the players when this is ticked": "Los jugadores ven los dibujos cuando esto está marcado",
  "Players see drawings": "Los jugadores ven los dibujos",
  "Clear drawings": "Borrar dibujos",
  "Label": "Etiqueta",
  "the fire barrel": "el barril de fuego",
  "Private note (only you see it)": "Nota privada (solo la ves tú)",
  "Players see this pin and its label": "Los jugadores ven esta chincheta y su etiqueta",
  "New note on the map": "Nota nueva en el mapa",
  "That is the most marks this map holds.": "Es el máximo de marcas que admite este mapa.",
  "There are no drawings to clear.": "No hay dibujos que borrar.",
  "Drawing": "Dibujo",
  "Drawing erased": "Dibujo borrado",
  "Drawings cleared": "Dibujos borrados",
  "Note added": "Nota añadida",
  "Note edited": "Nota editada",
  "Player tokens reveal the squares they can see, and walls block the view": "Las fichas de los jugadores revelan las casillas que ven, y los muros bloquean la vista",
  "Automatic vision": "Visión automática",
  "Sees": "Ve",
  "Remember explored": "Recordar lo explorado",
  "Drag on the map to draw a wall": "Arrastra sobre el mapa para dibujar un muro",
  "Wall": "Muro",
  "Drag to draw a door; click a door to open or close it": "Arrastra para dibujar una puerta; haz clic en una puerta para abrirla o cerrarla",
  "Door": "Puerta",
  "Clear walls": "Borrar muros",
  "That is the most walls this map holds.": "Es el máximo de muros que admite este mapa.",
  "There are no walls to clear.": "No hay muros que borrar.",
  "Wall added": "Muro añadido",
  "Wall removed": "Muro quitado",
  "Walls cleared": "Muros borrados",
  "Vision setting": "Ajuste de visión",
  "Drag from a point to lay a circle, cone or line, and see who is inside": "Arrastra desde un punto para colocar un círculo, un cono o una línea, y ver quién queda dentro",
  "Area": "Área",
  "Shape": "Forma",
  "Circle": "Círculo",
  "Cone": "Cono",
  "Line": "Línea",
  "Width": "Anchura",
  "Players see drawings and areas": "Los jugadores ven los dibujos y las áreas",
  "Inside: {names}": "Dentro: {names}",
  "Nobody is inside.": "No hay nadie dentro."
};
