/** Spanish for the web app's own interface text (the rules text is in es.mjs). */
export const UI_ES = {
  "Could not save in this browser. Use Export to keep your data.": "No se pudo guardar en este navegador. Usa Exportar para conservar tus datos.",
  "OK": "Aceptar",
  "Cancel": "Cancelar",
  "People": "Personas",
  "Sheet": "Ficha",
  "Log": "Historial",
  "Project Moon: The City": "Project Moon",
  "A free table companion. Your sheets are saved in this browser.": "La Ciudad: compañero de mesa gratuito. Tus fichas se guardan en este navegador.",
  "Fund": "Fondo",
  "Threat": "Amenaza",
  "Crew": "Equipo",
  "Add the 4 pregens": "Añadir los 4 prefabricados",
  "Nobody yet. Add the pregens, or make a character.": "Todavía no hay nadie. Añade los prefabricados o crea un personaje.",
  "Run downtime for all": "Tiempo libre para todos",
  "New scene for all": "Escena nueva para todos",
  "Welcome to the City": "Bienvenido a la Ciudad",
  "Add the four pregenerated characters, or make your own. Roll from the sheet; the log keeps every result.": "Añade los cuatro personajes prefabricados o crea el tuyo. Tira desde la ficha; el historial guarda cada resultado.",
  "Rolls and results appear here.": "Las tiradas y los resultados aparecen aquí.",
  "Clear log": "Borrar historial",
  "Duplicate": "Duplicar",
  "Delete": "Eliminar",
  "A group (+2 dice)": "Un grupo (+2 dados)",
  "Threat Clock": "Reloj de Amenaza",
  "Bond hook": "Gancho de Vínculo",
  "Detail": "Detalle",
  "No characters yet.": "Todavía no hay personajes.",
  "No Clocks.": "Sin Relojes.",
  "Add entry": "Añadir entrada",
  "Paid": "Pagado",
  "No Contracts yet.": "Todavía no hay Contratos.",
  "No target": "Sin objetivo",
  "Use Unbowed": "Usar Sin Doblegar",
  "Use it anyway": "Usarla igualmente",
  "Strength": "Fuerza",
  "Person": "Persona",
  "Temporary (ends with the scene)": "Temporal (termina con la escena)",
  "New character": "Personaje nuevo",
  "New Threat": "Amenaza nueva",
  "New crew": "Equipo nuevo",
  "There are no characters yet.": "Todavía no hay personajes.",
  "With nobody ticked, the crew is every character.": "Si no marcas a nadie, el equipo son todos los personajes.",
  "Delete {name}?": "¿Eliminar a {name}?",
  "This cannot be undone. Export first if you want a copy.": "No se puede deshacer. Exporta antes si quieres una copia.",
  "copy": "copia",
  "Delete every message in the log?": "¿Borrar todos los mensajes del historial?",
  "How to use this": "Cómo usar esto",
  "Close": "Cerrar",
  "Add the four pregens, or make a character. Click a Skill name to roll it.": "Añade los cuatro prefabricados o crea un personaje. Pulsa el nombre de una Habilidad para tirarla.",
  "The roll dialog adds Sin dice (matchup and Fit), attuned gear, Bonds, E.G.O. dice and Help. Pick a target to fill in its dice and Sin.": "El cuadro de tirada suma dados de Pecado (enfrentamiento y Encaje), equipo sintonizado, Vínculos, dados de E.G.O. y Ayuda. Elige un objetivo para rellenar sus dados y su Pecado.",
  "E.G.O. dice that show 1 or 2 are Complications. When E.G.O. drops, the Voice speaks in the log.": "Los dados de E.G.O. que muestran 1 o 2 son Complicaciones. Cuando baja el E.G.O., la Voz habla en el historial.",
  "Signature Techniques are on the Sins tab. Press New scene when a scene ends.": "Las Técnicas de Firma están en la pestaña Pecados. Pulsa Escena nueva cuando termine una escena.",
  "Your sheets are saved in this browser only. Use Export now and then to keep a file, and Import to load it on another device.": "Tus fichas se guardan solo en este navegador. Usa Exportar de vez en cuando para guardar un archivo, e Importar para cargarlo en otro dispositivo.",
  "To play together, press Room: the GM opens a room and players join with the code. Everyone sees the rolls; the GM sees each player's sheet.": "Para jugar juntos, pulsa Sala: el DJ abre una sala y los jugadores entran con el código. Todos ven las tiradas; el DJ ve la ficha de cada jugador.",
  "Import": "Importar",
  "Export": "Exportar",
  "Help": "Ayuda",
  "Importing replaces everything in this browser. Continue?": "Importar reemplaza todo lo de este navegador. ¿Continuar?",
  "Imported.": "Importado.",
  "That file is not a Project Moon save.": "Ese archivo no es una partida de Project Moon."
};
