"""Makes the web-sized copies of the vault's maps and tokens: JPEG maps (about 2100 px wide) and the small token PNGs.
Run from the webapp folder: python make_maps.py   (needs Pillow). The vault originals are only read."""
import json, pathlib, shutil
from PIL import Image

here = pathlib.Path(__file__).parent
vault = here.parent / "DM_Vault" / "04 Atlas VTT"
out = here / "maps"; out.mkdir(exist_ok=True)
tok = here / "tokens"; tok.mkdir(exist_ok=True)

MAPS = [  # id, vault file, title, grid on by default
    ("backstreet", "Backstreet_Market_Street", "Backstreet: market street", True),
    ("storefront", "Fixer_Office_Small_Storefront", "Fixer Office (small storefront)", True),
    ("branch", "Association_Branch_Office", "Association Branch", True),
    ("atrium", "Wing_Nest_Atrium", "Wing Nest Atrium", True),
    ("warehouse", "Syndicate_Warehouse_Hideout", "Syndicate Warehouse", True),
    ("breach", "Abnormality_Containment_Breach", "Abnormality Containment Breach", True),
    ("rooftop", "Rooftop_Chase", "Rooftop Chase", True),
    ("city", "City_Overview", "City Overview", False),
]
listing = []
for mid, stem, title, grid in MAPS:
    im = Image.open(vault / "Maps" / f"{stem}.png").convert("RGB")
    cell = 70
    if im.width > 2400:
        scale = 2400 / im.width
        im = im.resize((2400, round(im.height * scale)), Image.LANCZOS)
        cell = 0
    im.save(out / f"{mid}.jpg", "JPEG", quality=80, optimize=True)
    listing.append({"id": mid, "title": title, "file": f"maps/{mid}.jpg", "w": im.width, "h": im.height, "cell": cell, "grid": grid})
    print(mid, im.size, (out / f"{mid}.jpg").stat().st_size // 1024, "KB")

for f in (vault / "Tokens").glob("*.png"):
    shutil.copy(f, tok / f.name)
tokens = sorted(p.stem for p in tok.glob("*.png"))
(here / "js" / "maplist.mjs").write_text(
    "/** The bundled maps and tokens (generated by make_maps.py). Positions are in the shipped image's pixels. */\n"
    f"export const MAPS = {json.dumps(listing, indent=1)};\nexport const TOKENS = {json.dumps(tokens)};\n", encoding="utf8")
print("tokens:", len(tokens))
